### ISSUE TITLE
Possible bug in gridpack maker script.

### ISSUE THREAD

**Issue by andreypz** [cms-sw/genproductions#1032]
Hi,
Could someone have a look at the problem reported in [[1][1], [2][2]].
It looks like a bug in LHE file creator inside gridpacks, which prevents reading it in CMSSW.

Could you confirm that it is in fact a bug or not. And if it is, please suggest a patch which would allow to produce a samples via McM (without re-creating a gridpack). 

Thanks,
Andrey

[1]: https://hypernews.cern.ch/HyperNews/CMS/get/generators/3216.html
[2]: https://hypernews.cern.ch/HyperNews/CMS/get/generators/3216/1/1/1/1/1.html

**Comment by govoni** [comment]
Did you experience the issue yourself during production?
It looks like from the error message that the LHE file is corrupted.

**Comment by andreypz** [comment]
When I produced LHE files from the gridpack, using `./runcmsgrid.sh` command I did not get any errors.
I copied one file to my public area on afs: `/afs/cern.ch/user/a/andrey/public/HiggsDalitz/GridPacks-Oct2016/ggH120_mmg.lhe` if you'd like to have a look.

I did not run the hadronization steps myself. This is what our MC contact person (Gouranga) is trying to do. In the HN linked above he reports those errors.
It was [pointed out by Roberto](https://hypernews.cern.ch/HyperNews/CMS/get/generators/3216/1/1/1/1/1.html) that there is a mismatch in the XML tags:   
```<LesHouchesEvents version="3.0">``` in the beginning of the file  
```</LesHouchesEvent>``` at the end (missing an *s*)

So, could you confirm that this is indeed a bug in gridpack maker and the XML tags must be the same.
Then, do you have a suggestion on how to proceed with the sample production using such gridpacks?

**Comment by perrozzi** [comment]
@covarell is this still an open issue?

**Comment by covarell** [comment]
@bendavid was investigating, I understood that it is related only to a very specific use-case of MadSpin, all other processes are not affected. But I do not know if this was solved already (it is a bug of the MadSpin code itself, not related to CMS)

**Comment by andreypz** [comment]
The solution to fix the existing gridpacks was provided [in hypernews](https://hypernews.cern.ch/HyperNews/CMS/get/generators/3216/1/1/1/1/1/1/1/1/1/1/1/1.html) by Josh. 
But the fix in the scripts is still needed (for future productions), I think.

**Comment by bendavid** [comment]
I've already reported the issue+fix to the authors, so it should be fixed in future versions of madgraph.  Have not added the patches to the gridpack production scripts.
Indeed it only affects this somewhat specific use-case.

**Comment by perrozzi** [comment]
ok, I will close the issue then
