### ISSUE TITLE
Possible problem with gridpack due to taring

### ISSUE THREAD

**Issue by andreypz** [cms-sw/genproductions#1096]
There was another issue reported with Dalitz gridpacks. 
See [HN post](https://hypernews.cern.ch/HyperNews/CMS/get/generators/3273/1.html). There seem to be errors from tar which can not find some files.
I put one log file from gridpack here: _/afs/cern.ch/user/a/andrey/public/HiggsDalitz/gridpack_generation.log_ for you to have a look. (UPD: search file for word **fail**)

In principle, this does not seem to affect the event production with _runcmsgrid.sh_, so perhaps this is not a problem. We just need a confirmation.

Thanks

**Comment by perrozzi** [comment]
has this been solved?

**Comment by bendavid** [comment]
This error is spurious and can be ignored.

**Comment by bendavid** [comment]
(as long as the gridpack can indeed successfully produce events)
