### ISSUE TITLE
Add back bb4l

### ISSUE THREAD

**Issue by intrepid42** [cms-sw/genproductions#1117]
@yuanchao @perrozzi 

#1111 breaks bb4l process, please add back before merging powheg_gcc530 into master

**Comment by intrepid42** [comment]
Addition: It should be fine to remove [res_gfortran48.patch](https://github.com/cms-sw/genproductions/blob/master/bin/Powheg/patches/res_gfortran48.patch) in gcc530

**Comment by perrozzi** [comment]
(for the record, we are not going to merge powheg_gcc530 into master any time soon)

**Comment by intrepid42** [comment]
Ok, I guess this will have to be used for 2017 production?
Please add it back then before we have to produce the gridpacks.

**Comment by yuanchao** [comment]
A quick look at bb4l, it's actually a separated source repo. The res_gfortran48.patch should be indeed not needed as for gcc52+.  Just that I'm not sure if the RES version powheg takes rwgt PDF re-weights? It would be fine for gridpack production, but crash on LHE generation?

**Comment by intrepid42** [comment]
It takes the same rwgt file, see https://github.com/cms-sw/genproductions/blob/master/bin/Powheg/production/b_bbar_4l_NNPDF30_13TeV.input#L90
The <initrwgt> section that I added can be removed then, of course.

**Comment by yuanchao** [comment]
Actually, I'd prefer to keep the PDF lists in the run_cmsgrid.sh script. Calculating the PDF re-weightings doesn't seem much meaningful on grid production, right?

**Comment by intrepid42** [comment]
Hi Yuan, Powheg-res/bb4l takes the same rwl_file as Powheg-rwgt

**Comment by yuanchao** [comment]
@intrepid42 I mean leaving out the rwgt part in the input card and having run_pwg.py to add a common one. In this way, during the gridpack production, there's no unnecessary PDF weights calculations.

**Comment by intrepid42** [comment]
@yuanchao All right, that's exactly what I was trying to say :)

**Comment by perrozzi** [comment]
if I remember correctly this can be closed right?

**Comment by intrepid42** [comment]
Yep!

**Comment by yuanchao** [comment]
@intrepid42 Please also remember to remove the rwgt part in the b_bbar_4l input card, otherwise it won't work.

**Comment by perrozzi** [comment]
who shuold do that? Markus? can you please point to the relevant lines in the code?
