### ISSUE TITLE
Madgraph issues with condor @CMSConnect

### ISSUE THREAD

**Issue by khurtado** [cms-sw/genproductions#1193]
Hello,

@lorusso7 has been testing running gridpacks at CMS Connect and noticed an issue related to the `cluster.f` NLO instance in  madgraph:

The issue is triggered when running: `tt012j_5f_ckm_NLO_FXFX` with the Madgraph version used on the master branch. The gridpack gets stucked on the condor worker node on process P1_gg_ttxg/GF14, with the following output:

```
nFKSprocess: 10. Lower bound for tau is (taking resonances into account) 0.79264E-03  0.36600E+03  0.13000E+05
 bpower is   3.0000000000000000
 cluster.f: Error. Invalid combination.
 error
 ERROR in setclscales izero
Time in seconds: 0
```
That error appears to be triggered in this line:

https://github.com/bendavid/MadGraph5_aMC-NLO/blob/07621fd7bc806503cf0cbb197762aac421233956/Template/NLO/SubProcesses/cluster.f#L688

He did reproduce this workflow fine on LSF, so this might be related to condor (in which case it should also fail on lxplus using condor).
@lorusso7 pointed out there have been issues in the past related to `cluster_queue` that were workaround already. Looking into his`tt012j_5f_ckm_NLO_FXFX_gridpack/work/gridpack/mgbasedir/input/mg5_configuration.txt` file, the cluster queue is propely set to None for condor.

Any ideas of what the issue is or how to better debug this?

```
# MG5 MAIN DIRECTORY
mg5_path = /home/lorusso/cms_connect_kenyi/genproductions/bin/MadGraph5_aMCatNLO/tt012j_5f_ckm_NLO_FXFX/tt012j_5f_ckm_NLO_FXFX_gridpack/work/MG5_aMC_v2_4_2
cluster_queue = None
cluster_temp_path = /home/lorusso/cms_connect_kenyi/genproductions/bin/MadGraph5_aMCatNLO
```

Best,
Kenyi

**Comment by kdlong** [comment]
Hi Kenyi,

I think the name of this file is misleading. I believe that "cluster" here refers to the fact that the partons are being clustered. This looks like a physics error to me that has nothing to do with condor or LSF. Did you try multiple times and consistently see the error on CMS Connect but not LSF?

**Comment by khurtado** [comment]
@kdlong: Thanks! I think you are right. This doesn't seem to have anything to do with condor after all.

Looking further into it, I am able to reproduce this interactively from @lorusso7 's home area. The problem is related to the fact that `madevent_mintMC` didn't like the input in `GF14/mint_grids` (not sure when that file is created), but I don't know if this would be consistently triggered.

@lorusso7: Since you are already familiarized with this, could you re-run this on both places to double-check?

**Comment by lorusso7** [comment]
@khurtado yes, I re-run on both case

**Comment by perrozzi** [comment]
issue still open or solved by recent PRs?

**Comment by khurtado** [comment]
@perrozzi:  Still open, but @lorusso7 is running `tt012j_5f_ckm_NLO_FXFX` to see if this issue triggers again. This didn't seem to be connected to condor in the end... the subprocess that  failed before (P1_gg_ttxg/GF14) ran fine now, which is a good sign, but we are waiting for the whole run to finish just in case.

**Comment by khurtado** [comment]
So, it looks like everything went fine this time, so whatever happened the first teem seems to have been temporary. I will close this issue.
