### ISSUE TITLE
[mg] best way to distribute the condor python bindings for mg5_amc@nlo

### ISSUE THREAD

**Issue by khurtado** [cms-sw/genproductions#1212]
Hello,
During @lorusso `tt012j_5f_ckm_NLO_FXFX` test, I have noticed most madgraph jobs in that test run ran for less than 8 hours, with a very few going up to 24 to 35 hours.

This can be problematic while submitting to the Global Pool, because jobs are matched to currently running pilot jobs (pilots live for up to 48 hours and multiple real jobs run inside them) in the pool and you need to tell in advance how long a job is going to last at most (or it can be evicted when the pilot it is running at dies otherwise). The default in CMS Connect for this is 8 hours, which means a job can match to pilots that have been alive between 0 to 40 hours. Increasing the number to e.g 47 hours would mean a job can only match to very new pilots, which means matching to less resources. For the `tt012j_5f_ckm_NLO_FXFX`  run tests, one of the jobs ran 5 times on 5 different machines (first 4 got evicted after 8 to 24 hours) before completion. which translated into +120 hours wall clock time for that job since it started.

To fix this, I am thinking on implementing a list of “promised times” for a job. This is, something like: MaxWallTimeMins = [ 8*60, 24*60, 45*60]. Which means, if a job gets evicted after 8 hours, try 24 hours next and 45 next. The numbers in the list could be changed by the user and have the above by default.

Do you think that is reasonable? Otherwise, is there a way to tell if some particular jobs are going to take way longer than the others in madgraph so that we can set bigger times for those in advance?

**Comment by kdlong** [comment]
Hey @khurtado, as you know the issue with widely distributed run times is one we are basically stuck dealing with. I think the solution you propose is a quite a good one. We could also think about whether such an approach is possible outside of CMS connect. By the way, for faster responses, feel free to tag me, Qiang, and Vitaliano in your posts.

**Comment by vciulli** [comment]
I agree with @kdlong the proposed solution looks nice
Unfortunately I don't think there is any way to know in advance how long a specific job will take

**Comment by khurtado** [comment]
Thanks! Sounds good. I will implement this then.

**Comment by perrozzi** [comment]
any news on this?

**Comment by khurtado** [comment]
@perrozzi : I'm almost done with this, I ended up replacing `condor_q` external commands with condor python API schedd queries in madgraph first so that the code is more robust for this sort of thing. Will most likely make a PR with this plus other features by tomorrow.

**Comment by kdlong** [comment]
Adding this comment here since it might be the better location:

Thanks @khurtado, this is really nice! Once we have things finalized, I think we should also consider talking to the MadGraph authors about whether they would be interested in merging this into their master code.

How do you envision enforcing the requirement that the python bindings should be available at the site? For lxplus/Wisconsin I see it in /usr/lib64/python2.6/site-packages/. It doesn't appear to be an issue to import it and use in Pythia 2.7, however. 

To be more specific, I think we need to either require that sites have the python bindings or support both a condor_q based and a python bindings based approach.

**Comment by khurtado** [comment]
@kdlong : So, right now, source_condor.sh is invoked by both the condor and the cmsconnect submission scripts. This bash script looks for the python bindings in the environment and exits with error code 1 and some reason info otherwise. These libraries come with HTCondor binary releases and via condor-python RPMs and are compatible with python 2.6.x and python 2.7.x.

Since this is actually run inside a CMSSW environment (hence using python 2.7.x from cvmfs) maybe it makes sense to request these bindings to be available as part of the CMSSW external dependencies in cvmfs. What do you think?

**Comment by kdlong** [comment]
@khurtado: I discussed it a little with the Wisconsin computing people a while back when I was looking at this. There were some mixed feelings about whether it would make more sense to always take the library from the site-packages or to have it in CMSSW directly. I think it's something we should consult the computing experts about. @perrozzi @efeyazgan @govoni what's the best way to go about this?

**Comment by perrozzi** [comment]
without knowing yet the complete details, what @khurtado proposes sounds preferable to me, i.e. to include the requested packages into cmssw. we could consult with David Lange and Shahzad Muzaffar to hear what they think. Can you prepare a mail with some details?

**Comment by perrozzi** [comment]
can this be closed or is it still relevant?

**Comment by khurtado** [comment]
I think this can be closed, as this feature has been implemented in #1237 and merged already, but a new issue could be opened regarding @kdlong comments about the best way to distribute the condor python bindings (i.e Rely on the libraries to be included at the Sites vs including them as external dependencies in cvmfs/cmssw directly).

**Comment by perrozzi** [comment]
changed the title then ;-)

**Comment by vdutta** [comment]
Hi, posting here as suggested by @kdlong. The SUSY group uses condor submission at the UCSD T2 for producing signal scan gridpacks. In the past we had some modified version of the gridpack generation script with some site-specific hacks to enable condor submission but now we're trying to get things to work with the officially supported scripts. We ran into a problem with the check for the condor python bindings since it seems these are not available at the UCSD machines. We can check with the T2 support if it's possible to install the needed packages but it would be good to know if it's possible to have a workaround if not.

**Comment by khurtado** [comment]
Hi @vdutta : What version of condor is the T2 UCSD using?
There is a workaround for it:
```
1. Go to: https://research.cs.wisc.edu/htcondor/downloads/ and download the "stripped" binary tar.gz version for the right version of condor (e.g RHEL6 condor 8.6.x)
2. untar it somewhere accessible to all users. 
E.g /scratch/condor-8.6.5-x86_64_RedHat6-stripped
3. Add the python bindings to your python path
CONDOR_BINDINGS=/scratch/condor-8.6.5-x86_64_RedHat6-stripped/lib/python ; export PYTHONPATH=$CONDOR_BINDINGS:$PYTHONPATH
```
You can add the latest to a bash script that you source before using the madgraph or to the `submit_condor_gridpack_generation.sh` script if you want.

**Comment by vdutta** [comment]
Hi @khurtado, the condor version appears to be 8.4.11 but I don't see a binary listed for that version on the downloads site.

**Comment by khurtado** [comment]
@vdutta : The bindings in 8.4.12 should work just fine.

**Comment by vdutta** [comment]
Ok that's great, thanks! I'll give this workaround a try.

**Comment by kdlong** [comment]
@vdutta: Can you give a little more info on how you're submitting and where you see the problem?
 From your earlier message I understood that the issue comes up when the python bindings aren't found on the worker nodes, but I would have expected them to only be needed in by the master job which actually manages the submitted jobs (maybe I'm wrong here though...). Or do you submit the master job itself (running submit_condor_gridpack_generation.sh on the cluster) and allow it spawn other jobs?

**Comment by vdutta** [comment]
@kdlong : yes, at the moment I'm submitting the master job itself (submit_condor_gridpack_generation.sh) to the cluster ... is there another recommended way of doing it?

**Comment by kdlong** [comment]
This might just be a matter of preference. I think your approach is essentially what CMSConnect does. Personally I usually run the master job locally, inside screen/tmux so that it doesn't depend on the ssh connection. This has the advantage of allowing you to interact with the master job but the drawback of having to run it locally and deal with the long run time and possible large memory use.

**Comment by khurtado** [comment]
@vdutta: The workaround won't work in that case unless the directory that contains the python bindings is accesible by the worker node running the master and the environment for that job is properly set to find it.

As @kdlong said, you might be interested in CMS Connect, it allows you to generate gridpacks using all Tier Sites available for CMS ( including UCSD, of course). Here are the instruction for signing up to the service and generate gridpacks with it:

https://twiki.cern.ch/twiki/bin/view/CMS/QuickGuideMadGraph5aMCatNLO#Gridpack_generation_on_the_grid

Running the script with `nohup` allows you to run the master in background and log out of ssh session safely. Also, CMS Connect submits most of the heavy work in the master as a condor job for you already, it only leaves the condor job management and I think the madspin step, so it doesn't stress the system too much.

**Comment by kdlong** [comment]
Thanks @khurtado. Is there any implementation in CMSConnect (or expectation in the future) of having priority associated to specific sites? For users of big Tier 2's (Wisconsin, UCSD) the priority we get from submitting directly to our T2 is almost always faster than submitting to the global pool with CMSConnect.

**Comment by khurtado** [comment]
@kdlong : Yes, this is more of a Global Pool thing rather than a CMS Connect specific feature, but it is possible to give local users of a T2/3 priority over other CMS users.
Would you be willing to test? If so, I can create another issue and we can discuss there

**Comment by kdlong** [comment]
@khurtado: I'd be happy to test, it would be a very nice feature to have.

**Comment by vdutta** [comment]
Hello @kdlong and @khurtado, in the meantime I tried the condor submission by just running the master job locally, so the python bindings should be available to the master job. However, I still see the same error eventually:
root: could not import htcondor python API: 
No module named htcondorESC[0m
Do you have any ideas why this would be? Thanks!

**Comment by kdlong** [comment]
Did it get properly added to your python path? At Wisconsin I do:

PYTHONPATH=$PYTHONPATH:/usr/lib64/python2.6/site-packages
python -c "import htcondor; print htcondor"

I can see that the path was set properly. Does this work for you?

**Comment by vdutta** [comment]
Hi @kdlong: Yes, this works for me:
<module 'htcondor' from '/usr/lib64/python2.6/site-packages/htcondor.so'>
and I printed out the PYTHONPATH just now from the submit script:
:/usr/lib64/python2.6/site-packages

**Comment by khurtado** [comment]
@vdutta 

For a full test, can you try the following?
```
python -c 'import htcondor; schedd = htcondor.Schedd(); print schedd'
```

**Comment by vdutta** [comment]
@khurtado: This is what I get:
<htcondor.Schedd object at 0x7f53a8cd4e10>

**Comment by khurtado** [comment]
That's strange then. 
Just to be completely sure, the other object loaded from htcondor is JobAction:
```
python -c 'import htcondor; schedd = htcondor.Schedd(); print htcondor.JobAction.name'
```
If the above doesn't give you any errors, try replacing 
```
PTYHONPATH=$PYTHONPATH:/usr/lib64/python2.6/site-packages
``` 
with
```
export PTYHONPATH=$PYTHONPATH:/usr/lib64/python2.6/site-packages
```
in the condor submit script.

**Comment by khurtado** [comment]
@vdutta:
What I do when I want to debug better is the following:
1. Check you condor\_q and hold a job `condor_hold <clusterId>`
2. Create 3 empty files somewhere: `mkdir $HOME/log/; cd $HOME/log; touch condor.log condor.out condor.err`
3. Edit your held job to redirect output to your files with condor\_qedit (here, you need to full PATHs, condor\_qedit won't accept environment variables)
```
ls $HOME/log
/home/user/log
condor_qedit <clusterId> UserLog "/home/user/log/condor.log"
condor_qedit <clusterId> Err "/home/user/log/condor.err
condor_qedit <clusterId> Out "/home/user/log/condor.out"
condor_release <clusterId>
```
After that, your job should start redirecting all messages to these files so you can debug.

**Comment by vdutta** [comment]
@khurtado: Ok, does this mean I have to rerun the master job and wait for it to again get to the stage of submitting the condor jobs? Or is the condor submit command saved somewhere? The problem I saw was that the jobs died almost as soon as they were created, so it would be tricky to hold a job in time.

**Comment by khurtado** [comment]
You would need to rerun the master. As soon as you see the jobs being submitted, you can just do `condor_hold yourusername`, to hold whatever is there in the queue for you at that point.

Note this is not the original problem anymore though, so you might want to open a new issue.

**Comment by kdlong** [comment]
@vdutta This seems like a MadGraph specific issue unrelated to condor, I think it's best to open another issue/post on the generators hypernews
