### ISSUE TITLE
Problem  for gridpack W+j production in Madgraph V2_5_1 

### ISSUE THREAD

**Issue by lorusso7** [cms-sw/genproductions#1220]
Dear experts, @kdlong, @qliphy,   
for the Madgraph validation tests I have tried to produce W+jet gridpack in version 2.5.1.
The run and proc cards for the process are shown below [1]. 

To produce the gridpack I have used the "standard" receipt (for lsf submission) described in [2] with "memoryInMBytes=30000 MB" and 2nw queue. The CMSSW release is CMSSW_7_1_23 with ARCH=slc6_amd64_gcc481. 

The gridpack output is shown in [3]: in particular the all jobs end but the cross section is not valuated and so the LHE events productions does not work [4]. 

I have done the same gridapck with "use_syst=False" but the same problems appear.
I have understood  that Qiang has encountered the same issue in the gridapack generation.
Do you have any suggestion to fix the problem?
Do I produce the same gridpack in V2.5.4 in the actual branch mg25x [5]?

[1]
[WJetsToLNu_HT-incl_proc_card.txt](https://github.com/cms-sw/genproductions/files/1121371/WJetsToLNu_HT-incl_proc_card.txt)
[WJetsToLNu_HT-incl_run_card.txt](https://github.com/cms-sw/genproductions/files/1121370/WJetsToLNu_HT-incl_run_card.txt)

[2] https://twiki.cern.ch/twiki/bin/view/CMS/QuickGuideMadGraph5aMCatNLO#Quick_tutorial_on_how_to_produce

[3] [STDOUT.txt](https://github.com/cms-sw/genproductions/files/1121391/STDOUT.txt)

[4] [OUT_lhe.txt](https://github.com/cms-sw/genproductions/files/1121430/OUT_lhe.txt)

[5]https://github.com/cms-sw/genproductions/blob/mg25x/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L114

**Comment by kdlong** [comment]
Thanks Lorenzo. I  see a similar discussion here: https://answers.launchpad.net/mg5amcnlo/+question/644315

I'm not sure why there is no output, but probably an individual subprocess failed as in the launchpad discussion. Can you try the suggestion made by Olivier, setting "False = mc_grouped_subproc" in the run_card.dat?

I'm having trouble finding more information on this setting. Maybe @bendavid knows more?

**Comment by lorusso7** [comment]
I try the test with "False = mc_grouped_subproc"

**Comment by vciulli** [comment]
@kdlong @qliphy Do you think it is better to do this test still with 2.5.1 or should Lorenzo move to a more recent version (2.5.4 or 2.5.5)? 
We could also try CMSConnect as we said yesterday

**Comment by qliphy** [comment]
@vciulli @kdlong @lorusso7   I am now doing 2 tests for W01234MLM under 2.5.5 w/o  "False = mc_grouped_subproc".  Will update you later.     I think testing at CMSConnect  is a good idea.

**Comment by qliphy** [comment]
@vciulli @kdlong @lorusso7   

Here is the status of the 2 tests on MG255 W01234MLM I have been doing these several days:

(1) The test with "False = mc_grouped_subproc" is still ongoing.

(2) The other test has finished successfully.  I have tested running the gridpack [1], and everything looks fine to me.  In this test, I have modified two places in run_card.dat:
Nevents 1500->5000
bwcutoff 1500->150
I think bwcutoff might be the reason for previous NAN problem.

The command I used is:
./submit_gridpack_generation.sh 25000 25000 2nw WJetsToLNu_HT-incl cards/lorusso/WJetsToLNu_HT-incl 2nw

with the cards in [1].



[1]  in my eos region at lxplus: /store/user/qili/mg25x/mg255

**Comment by bendavid** [comment]
I thought we agreed not to use large bwcutoff for w+jets anymore due to previously observed inconsistencies.  (And just produce p p > l+ vl, etc instead)

**Comment by vciulli** [comment]
> On 6 Jul 2017, at 09:22, Josh Bendavid <notifications@github.com> wrote:
> 
> I thought we agreed not to use large bwcutoff for w+jets anymore due to previously observed inconsistencies. (And just produce p p > l+ vl, etc instead)
> 
yes, that is correct 
I guess these tests started from the old datacard sets… 
@lrusso: the latest version of the cards for W+jets (those you used for MG 2.4.2) are not in github? could you please make a pull request?

**Comment by qliphy** [comment]
Just to add that the other test with "False = mc_grouped_subproc" is still ongoing.  It takes much longer time than without this line.   

Anyway, I agree that we should update the cards for W+jets.

**Comment by perrozzi** [comment]
is this solved or still open?

**Comment by lorusso7** [comment]
The gridpack production with  "False = mc_grouped_subproc" option is still running.

**Comment by bendavid** [comment]
Ok, but I thought we agreed to simply move to the new cards without the large bwcutff and producing l v directly.  In this case it should be run without changing the mc_grouped_subproc option as usual.  Has this been tried yet?

**Comment by qliphy** [comment]
smaller bwcutoff  indeed works, and the gridpack (W->lv, not lv directly) has been produced and tested successfully [1]

 "False = mc_grouped_subproc" indeed make MG runs quite slowly.  We should not got with this.

[1] in my eos region at lxplus: /store/user/qili/mg25x/mg255

**Comment by bendavid** [comment]
Ok but that configuration is not acceptable for general production, since some groups care about the off-shell phase space.  Again I thought the agreement was to go with p p > l v with the standard bwcutoff, and then this is the configuration which should be tested.

**Comment by bendavid** [comment]
(in fact the example cards should also be updated accordingly)

**Comment by perrozzi** [comment]
any news? is this github issue still relevant or superseeded/obsolete?

**Comment by perrozzi** [comment]
I believe this thread is obsolete, closing it.
Please reopen in case is still needed
