### ISSUE TITLE
Wrong gridpack directory path on eos? 

### ISSUE THREAD

**Issue by vciulli** [cms-sw/genproductions#1222]
While trying to upload some new gridpack on cvmfs I noticed that there exists a dir 
/eos/cms/store/group/phys_generator/gridpacks
which is not mapped to cvmfs.
Is that of any use? 
If not maybe it should be removed to avoid confusion. 
The right directory for uploading to cvmfs is 
/eos/cms/store/group/phys_generator/cvmfs/gridpacks

**Comment by perrozzi** [comment]
Thanks Vitaliano, I will move the gridpacks if not existing already and remove /eos/cms/store/group/phys_generator/gridpacks

**Comment by perrozzi** [comment]
mmm, don't have delete permissions, we need to contact cms computing. In the meanwhile I am contacting the authors of the gridpacks

**Comment by perrozzi** [comment]
solved (i.e. wrong directory removed)
