### ISSUE TITLE
Update MadGraph examples to 2017 PDF recommendation 

### ISSUE THREAD

**Issue by kdlong** [cms-sw/genproductions#1223]
Implement list of PDF sets in [1] into example cards and test performance.

For NLO MadGraph: Change this line to appropriate LHAPDF numbers 

https://github.com/cms-sw/genproductions/blob/mg25x/bin/MadGraph5_aMCatNLO/cards/examples/wplustest_5f_NLO/wplustest_5f_NLO_run_card.dat#L65

For LO MadGraph: Change calls in Syscalc/update to new "systematics" tool.

https://github.com/cms-sw/genproductions/blob/mg25x/bin/MadGraph5_aMCatNLO/runcmsgrid_LO.sh#L94-L120

https://cp3.irmp.ucl.ac.be/projects/madgraph/wiki/Systematics

**Comment by govoni** [comment]
a curiosity: how does ng5nlo know that for some pdfs we want only the central value, while for others we want also the uncertainty variations?

**Comment by bendavid** [comment]
There's a syntax for this, but I forget what it is at the moment...

**Comment by govoni** [comment]
@kdlong @vciulli @qliphy : do you happen to know how to do it? This we need, for the tests of the PDF sets configuration, which is here https://docs.google.com/spreadsheets/d/1YjhruLPvmwqoA1YZPgmU5H9T3ELnYnriHgO9DrJQoxk/edit#gid=0

**Comment by kdlong** [comment]
From https://cp3.irmp.ucl.ac.be/projects/madgraph/wiki/Systematics#NLO, it looks like something like 29000@0 is supported, but I haven't yet tried this out.

**Comment by govoni** [comment]
Ok, thanks. So how far are we, from having an example that implements the pdf weights we planned to include in the production?

**Comment by perrozzi** [comment]
according to the link posted by kdlong EVERY request will need to implement the list of reweightings... probably this should be automatized inside gridpack_generation.sh right?
as far as I understand/remember also for LO the same trick will be needed.
Can anybody confirm?

**Comment by bendavid** [comment]
For NLO at least I think we will continue to use the "on the fly" method, where everything is specified in the run card as before.

**Comment by bendavid** [comment]
Ah, but indeed since it is possible to use the python method also for NLO, maybe this is preferred in order to have more coherence between LO and NLO.

In this case I think the thing to do first is to migrate the LO systematics from syscalc to the new python method to understand how to implement it (then decide what to do for NLO).

**Comment by perrozzi** [comment]
has anybody checked/implemented/tested the python method? if not, is there a reference/example?

**Comment by bendavid** [comment]
This twiki page is the reference.
(This is actually the first I realized that the python method can also be used for NLO.  As said, for NLO it is possible to use the multiple pdf weights in the "on the fly" method, simply specifying everything in the run cards, and this is what I tested previously and what is currently in some of the example cards.)

**Comment by perrozzi** [comment]
ok, looking at the twiki
https://cp3.irmp.ucl.ac.be/projects/madgraph/wiki/Systematics#Systematicspythonmodule
and assuming that at first order we don't want to specify stuff in the run_card, we need to follow this:
[...] The "systematics" module can be called externally. It is callable via the Madevent interface [...]
how to do that?

**Comment by perrozzi** [comment]
shall we simply call Madevent like this
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L596-L597
using the PDF reweighting arguments?

**Comment by kdlong** [comment]
Initial implementation in #1243

**Comment by kdlong** [comment]
InInitial tests suggest that NLO jobs take much longer with this implementation. This is maybe not a surprise since the calculation needs to be performed for each PDF set. A major concern is that the job splitting in MadGraph seems fixed independent of the number of PDF sets run, but if 1000 variations are evaluated per job it takes considerably longer. For the NLO W+ (no FxFx) some jobs are running for > 24 hours. This makes me doubt that this approach will work for larger jobs. @bendavid, do you know if there's any way to calculate PDF uncertainties after the initial run with 2.4.2 or is it only possible with "systematics" in 2.5?

**Comment by bendavid** [comment]
The old method (calculating pdf weights as part of the event generation) should still work in both 2.4.x and 2.5.x.  I tested this in 2.4.x with around 500 weights and didn't see any significant slowdown.

If the python method is too slow for NLO agreed we can stay with the runcard+event generation method.

**Comment by bendavid** [comment]
Also we obviously have control over the splitting at event generation time, so if the pdf weights take longer to compute we can simply submit smaller jobs.

**Comment by kdlong** [comment]
I was saying the opposite, that the event generation weights seems slower. This could be an unrelated issue with the cluster, for example. But wouldn't you expect 1000 PDFs to be slower than 1? 

And how do you control the event splitting?

**Comment by bendavid** [comment]
Yes it was slower but only a factor of 2 or 3.  (Ie 2s per event to 5s or so). Which process are you testing with?

Job splitting for pilot events produced at gridpack generation time is controlled from the run card.  Job splitting for production of events using the gridpack afterwards of course by computing using the time per event in mcm (which should obviously include any additional time needed to compute pdf weights)

**Comment by kdlong** [comment]
I'm using wplustest_5f_NLO at the moment. It's being running for 36 hours, which is much longer than usual. I didn't notice such a difference locally, but I didn't careful control the conditions on anything yet. Could cvmfs reading be a non-negligible factor?

**Comment by bendavid** [comment]
I wouldn't expect that, but it's possible.  Which site are you testing at?

**Comment by khurtado** [comment]
@kdlong @bendavid : Something to keep in mind is that when @lorusso7 tested CMS Connect with `tt012j_5f_ckm_NLO_FXFX` a while ago, a very few jobs took longer than 24 hours. A factor of 2 or 3 would mean going over the current 48 hours pilot lifetime limit in the CMS Global Pool, which would be an issue, so making the jobs smaller in advance would be needed in those cases.

**Comment by kdlong** [comment]
Agreed @khurtado. Though I think the timing issues may be with my cluster, when using CMSConnect I didn't see such striking differences. From my perspective this is ready to be tested more extensively. I have tested the LO and NLO examples on top of Kenyi's fixes and see no issues so far.

**Comment by bendavid** [comment]
If the issue turns out to be site-specific, it's indeed possible there is a misconfiguration/suboptimal configuration of CVMFS caching/etc which only shows up under the increased load from the additional PDF's.

**Comment by perrozzi** [comment]
I assume this can be closed as far as mg2.4 is concerned, right?
probably still worth to leave it open for 2.5 (in that case better to rename the issue)

**Comment by kdlong** [comment]
I think it can be closed. I'll open a separate issue for MG 2.5.5 because there are still some issues to discuss there.
