### ISSUE TITLE
Verify correct installation/usage of ninja and collier for mg5_amc in 25x branch

### ISSUE THREAD

**Issue by bendavid** [cms-sw/genproductions#1230]
Since the Collier library has been added to recent madgraph versions, we should make sure it is being correctly installed and used (it should be done automatically, but there were some technical issues which prevented this from working with Ninja in our scripts in the past).  There should be some performance improvement associated with this.

**Comment by kdlong** [comment]
It looks to me like Ninja is being used in 2.5.5, but this also appears to be the default behavior.

**Comment by bendavid** [comment]
And Collier?

**Comment by kdlong** [comment]
It seems to be not installed by default. Example output below.

First output using loop matrix-elements has been detected. Now asking for loop reduction:                                                           
For loop computations, MadLoop requires dedicated tools to perform the reduction of loop Feynman diagrams using OPP-based and/or TIR approaches.

Which one do you want to install? (this needs to be done only once)
1. cuttools  (OPP) [0711.3596]   : will be installed (required)
2. iregi     (TIR) [1405.0301]   : will be installed (required)
3. ninja     (OPP) [1403.1229]   : will be installed (recommended)
4. collier   (TIR) [1604.06792]  : do not install
5. golem     (TIR) [0807.0605]   : do not install
6. pjfry     (TIR) [1112.0500]   : do not install
You can:
 -> hit 'enter' to proceed
 -> type a number to cycle its options
 -> enter the following command:
    {tool_name} [install|noinstall|{prefixed_installation_path}]

If you are unsure about what this question means, just type enter to proceed.
The answer to the previous question is not set in your input file
Use 0 value
set golem ''
save options golem
save configuration file to /data/kelong/genproductions/bin/MadGraph5_aMCatNLO/wplustest_5f_NLO/wplustest_5f_NLO_gridpack/work/MG5_aMC_v2_5_5/input/mg5_configu
ration.txt
save options golem
save configuration file to /data/kelong/genproductions/bin/MadGraph5_aMCatNLO/wplustest_5f_NLO/wplustest_5f_NLO_gridpack/work/MG5_aMC_v2_5_5/input/mg5_configu
ration.txt
set pjfry ''
save options pjfry
save configuration file to /data/kelong/genproductions/bin/MadGraph5_aMCatNLO/wplustest_5f_NLO/wplustest_5f_NLO_gridpack/work/MG5_aMC_v2_5_5/input/mg5_configu
ration.txt
save options pjfry
save configuration file to /data/kelong/genproductions/bin/MadGraph5_aMCatNLO/wplustest_5f_NLO/wplustest_5f_NLO_gridpack/work/MG5_aMC_v2_5_5/input/mg5_configu
ration.txt
set collier ''
save options collier
save configuration file to /data/kelong/genproductions/bin/MadGraph5_aMCatNLO/wplustest_5f_NLO/wplustest_5f_NLO_gridpack/work/MG5_aMC_v2_5_5/input/mg5_configu
ration.txt
save options collier
save configuration file to /data/kelong/genproductions/bin/MadGraph5_aMCatNLO/wplustest_5f_NLO/wplustest_5f_NLO_gridpack/work/MG5_aMC_v2_5_5/input/mg5_configu
ration.txt
install ninja
   You are installing 'ninja', please cite ref(s): arXiv:1203.0291, arXiv:1403.1229, arXiv:1604.01363.

**Comment by bendavid** [comment]
hmm, ok, I thought in standalone madgraph it was installed by default, but maybe I'm misremembering.

If it's not installed by default with standalone madgraph then I agree we don't need to worry about it for now.

**Comment by kdlong** [comment]
Should we prefer Collier? If so we can edit things to chose it, but it's not the default at the moment. Or we can just stick to Ninja and close this. What do you think?

**Comment by bendavid** [comment]
Hi,
Can you check what is done with madgraph standalone?

**Comment by kdlong** [comment]
It gives the exact same message, with ninja the default choice.

**Comment by bendavid** [comment]
Ok, does collier get installed automatically though?

**Comment by kdlong** [comment]
I believe by default it's not installed.

**Comment by bendavid** [comment]
Alright, then I'm happy to have the same in our scripts.

**Comment by perrozzi** [comment]
can the issue be closed?

**Comment by bendavid** [comment]
Yes.
