### ISSUE TITLE
merge powheg_gcc530 branch into master

### ISSUE THREAD

**Issue by perrozzi** [cms-sw/genproductions#1233]
With the new workflow explicitly sourcing scram_arch and cmssw from runcmsgrid.sh
we can move the production to powheg gcc530 without problems.
We can clone the current master branch to have a branch, for instance named powheg_gcc48x, compatible with gcc480 for back-compatibility.

**Comment by efeyazgan** [comment]
OK (with naming the branch powheg_gcc48x as well)

**Comment by perrozzi** [comment]
@covarell @yuanchao comments?

**Comment by covarell** [comment]
No comments, but we need #1232 and to make a final check that we did not miss anything of the latest changes in the master branch during the forward-porting. Thanks!

**Comment by perrozzi** [comment]
powheg_gcc48x branch created cloning master 
https://github.com/cms-sw/genproductions/tree/powheg_gcc48x

**Comment by perrozzi** [comment]
current diff seems reasonable
https://github.com/cms-sw/genproductions/compare/powheg_gcc530

**Comment by covarell** [comment]
I am just a bit puzzled about the "file changes" shown in this comparison. For example, why the macros lheMacros/*LheFiles.cpp appear as entirely green even if they are present in both branches.

However, this is just a detail, I think we can proceed.

**Comment by perrozzi** [comment]
yes indeed, there are many things which are marked as changes while they are not.
I believe github gets fooled by the fact that the same change has been applied to different branches through different commits.
Yes please proceed asap!
Thanks

**Comment by covarell** [comment]
Ahem...
If I need to do that, I would need line-by-line github instructions, please.  :-)

**Comment by perrozzi** [comment]
I don't think is a git issue but more of a github visualization issue,
I am pretty sure things will work ok in the command line. can you give it a quick try?
I will try too in the meanwhile

**Comment by perrozzi** [comment]
cfr https://github.com/cms-sw/genproductions/pull/1239

**Comment by perrozzi** [comment]
#1239 merged into a newly created branch called "master_powheg_gcc5" to be used for testing before to actually merge to master
@covarell @yuanchao et al can you please give a look and start the testing?

**Comment by perrozzi** [comment]
https://github.com/cms-sw/genproductions/pull/1255 merged, closing the issue
