### ISSUE TITLE
Update MadGraph v2.5.5 systematics (PDFs and scales including functional form)

### ISSUE THREAD

**Issue by kdlong** [cms-sw/genproductions#1270]
Implement list of PDFs [1] in MadGraph v2.5.5 using "systematics" python module.

This is in principle already tested and working (pull request to come shortly), but there are a few issues worth discussing: @perrozzi @efeyazgan @vciulli @qliphy @bendavid 

1) It's also possible to include weights for different functional forms of the dynamic scale. The default MadGraph scale choice is not simple, so having values like H_{T}/2 would be useful in some cases. Do we want to include these?

2) In the current version, the weight ids start from 1001 and count by one, not differentiating between different types of weights. In the old samples, PDF weights started at 2000, and we extended this to 3000s and 4000s for the POWHEG samples. This has the nice feature that you can easily distinguish where one type of weight ends and the next begins. I asked about such a feature [3] and the authors are receptive. Do others think it's worth trying to add this as a patch when it's implemented?

[1] https://docs.google.com/spreadsheets/d/1YjhruLPvmwqoA1YZPgmU5H9T3ELnYnriHgO9DrJQoxk/edit#gid=0
[2] https://cp3.irmp.ucl.ac.be/projects/madgraph/wiki/Systematics
[3] https://answers.launchpad.net/mg5amcnlo/+question/654417

**Comment by bendavid** [comment]
For FXFX merging I think one does not have the freedom to change the functional form without invalidating the merging.  (But doesn't hurt to ask the authors about it.)

**Comment by perrozzi** [comment]
yes to both questions for me, thanks a lot

**Comment by kdlong** [comment]
I wondered about the FxFx scale choice as well. I added the question to the launchpad thread. In any case, would including the dynamic scale weights be worth it in samples where this does make sense? It can also be specified directly in the run card, so if we don't do it by default it's still possible for someone to explicitly request it.

**Comment by kdlong** [comment]
The authors confirm that only the central dynamic scale is sensible for the FxFx case. Do you think it's worth having variations by default for other samples or should we only include these if they're explicitly requested?

**Comment by perrozzi** [comment]
by default is good, unless this particular weight computation is very long to do or other issues

**Comment by perrozzi** [comment]
cfr https://github.com/cms-sw/genproductions/pull/1286/files
