### ISSUE TITLE
[mg] Madgraph jobs longer than 48 hours and Global Pool limits

### ISSUE THREAD

**Issue by khurtado** [cms-sw/genproductions#1283]
Hello,

Making this issue to keep it in mind for the near future.
I am not aware of any workflow having single jobs going over 48 hours on average at this point, but I am making this issue to remind people that is the actual limit of the Global Pool, hence CMS Connect.

If this is an issue now, let me know. If you think this will become an issue soon, let me know. There are 2 approaches in case this become a problem:

- Reduce the walltime by decreasing the number of events per job in madgraph cards
- Coordinate with the Submission Infrastructure team to provide special glideins with lifetimes longer than 48 hours (e.g 72 hours?) 

If the first isn't hard, I would rather go with that option at that point, but I will need to know if the second option becomes necessary.

**Comment by bendavid** [comment]
If the long jobs are coming in the phase space integration step, then decreasing the number of events per job will have no impact.

**Comment by khurtado** [comment]
@bendavid : Is there any other approach that can be done within madgraph in that case, or is the second option the only viable solution in such scenario?

**Comment by bendavid** [comment]
No, the second option would be the only solution in that case.

**Comment by khurtado** [comment]
Okay, let me know if/when there is such need so that I can coordinate with the SI team then.

**Comment by khurtado** [comment]
An update on this: I talked to the SI team and was confirmed there are some sites with glideins of 60 to 70 hours (5 Tier 1s and 6 Tier 2s), so this shouldn't be an issue unless there are gridpacks requiring more than that.
