### ISSUE TITLE
[mg] Increasing priorities on your T2, when submitting from CMS Connect

### ISSUE THREAD

**Issue by khurtado** [cms-sw/genproductions#1288]
Hello,

Just so you know, if you have a local allocation on a CMS Tier 2/3 and you would like to give priority for your jobs over other CMS users when using CMS Connect, this is already possible within the Global Pool, but requires coordinating with your Site administrator.

The steps are the following:

1. Look for your Site in the DB and contact your Site Admin (or Site executive): https://cmsweb.cern.ch/sitedb/prod/sites/
2. Look for your grid/CERN username: https://cmsweb.cern.ch/sitedb/prod/people
3. Ask your Site admin to add your username to the SITECONF local priority group
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CompOpsCustomizedGlideins#local_group

The last step requires your admin to be able to modify the SITECONF in the cern gitlab: https://gitlab.cern.ch/SITECONF , as mentioned in the twiki.

Once this is done, allow a few hours for the changes to propagate into CVMFS. That's it, no changes on genproductions is needed. Additionally, this will give you extra priority on CRAB jobs too.

@kdlong : Can you try these instructions out and give some feedback on the new performance?
For the test, you can type:
```
source /etc/ciconnect/set_condor_sites.sh T2_US_Wisconsin
```
before submitting your jobs on CMS connect to submit only to your T2 Site.
After that, we can add the instructions to the twiki if desired.

**Comment by kdlong** [comment]
Sorry for the delay, it's taking a little time to get things going on our side, but the computing people at UW are helping me with this and we're making some tests now. I'll let you know how it goes.

**Comment by khurtado** [comment]
Thanks for the update @kdlong

**Comment by kdlong** [comment]
Update from the Wisconsin computing team:

So far so good.  Our records show that pilots ran on our CE with the
following attribute:

x509UserProxyFQAN =
"/DC=ch/DC=cern/OU=computers/CN=cmspilot02/vocms080.cern.ch,/cms/local/Role=pilot/Capability=NULL,/cms/dcms/Role=NULL/Capability=NULL,/cms/escms/Role=NULL/Capability=NULL,/cms/itcms/Role=NULL/Capability=NULL,/cms/local/Role=NULL/Capability=NULL,/cms/Role=NULL/Capability=NULL,/cms/uscms/Role=NULL/Capability=NULL"

Note /cms/local/Role=pilot in the FQAN.  That indicates that the glidein
factory did submit "local" pilots, presumably in response to the demand
for resources by Kenneth's jobs.

The existence of these extra pilots should already have resulted in a
modest priority improvement.  We will investigate what additional
policies can be implemented in CHTC.

**Comment by khurtado** [comment]
Thanks for the info! Do you notice any speed up? If so, should we document this in the twiki?

**Comment by kdlong** [comment]
Hi @khurtado,

Sorry for not following up on this. I wouldn't say I noticed a huge difference, but according to the computing people it worked successfully. If you want to document it this could be useful in the future.
