### ISSUE TITLE
include all the datacards inside the mg5_amc@nlo gridpack

### ISSUE THREAD

**Issue by perrozzi** [cms-sw/genproductions#1293]
all the datacards used to create a mg5_amc@nlo gridpack should be shipped in the final gridpack in a clear and easy-to-identify way. Like in the main directory.
so far this is not the case. some cards are included into process/Cards, but is not easy to retrieve/understand

**Comment by bendavid** [comment]
Suggest to just copy the whole input directory to "inputs" or something and add it to the tarball.

**Comment by perrozzi** [comment]
https://github.com/cms-sw/genproductions/pull/1299 and https://github.com/cms-sw/genproductions/pull/1300
