### ISSUE TITLE
[2017 MC v2] checking POWHEG compilation and weights

### ISSUE THREAD

**Issue by perrozzi** [cms-sw/genproductions#1307]
* Currently **POWHEG** set to CMSSW_9_1_1 (cfr [twiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/PowhegBOXPrecompiled#Download_all_the_necessary_scrip) )
      * Does it have all the needed PDFs?
      * Probably better to move to CMSSW_9_2_11 ? 

~

   * Currently **MG5_aMC@NLO** set to CMSSW_7_1_28 (cfr [generation script](https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L47) )
      * Likely OK to stay with that unless newer version require an update

**Comment by perrozzi** [comment]
**POWHEG** instructions moved to CMSSW_9_2_11

**Comment by perrozzi** [comment]
need to wait for the latest and greatest 92x and 71x to include all the required PDFs
https://github.com/cms-sw/cmsdist/pull/3419/files
https://github.com/cms-sw/cmsdist/pull/3417

**Comment by perrozzi** [comment]
David suggests to move to 93x instead of 92x
https://github.com/cms-sw/cmsdist/pull/3415#issuecomment-329801298
This means to move from gcc530 to gcc630.
We need to test POWHEG in this configuration...
Unless anybody has ideas/arguments to stick to 92x

**Comment by perrozzi** [comment]
Currently testing **compilation** for **all** processes using
CMSSW_9_2_12 (gcc530)
CMSSW_9_3_0_pre5 (gcc630)

**FAILING** so far:
weakinos (gcc630 and gcc530)
Wbbj (gcc630 and gcc530)
Wbb_dec (gcc630)

**Comment by perrozzi** [comment]
**POWHEG** instructions moved to CMSSW_9_3_0

**Comment by agrohsje** [comment]
@perrozzi 
Hi Luca, I just  tested gg_H using  
https://raw.githubusercontent.com/cms-sw/genproductions/master/bin/Powheg/examples/gg_H_quark-mass-effects_withJHUGen_NNPDF30_13TeV/JHUGen.input 
and 
https://raw.githubusercontent.com/cms-sw/genproductions/master/bin/Powheg/examples/gg_H_quark-mass-effects_withJHUGen_NNPDF30_13TeV/gg_H_quark-mass-effects_NNPDF30_13TeV.input 
but didn't encounter any problem in gcc 630. Modulo this warning that should be followed up: 
pwhg_cpHTO_reweight.f:864:19:

        res(5,1)= -1/2*(rz2**2-3.d0*rz4)
                   1
Warning: Integer division truncated to constant '0' at (1) [-Winteger-division]

I can also generate events. I followed the Powheg TWiki using:
export SCRAM_ARCH=slc6_amd64_gcc630
cmsrel  CMSSW_9_3_0_pre5

Is there anything else you did?

**Comment by agrohsje** [comment]
Two  more follow-ups. 
1.)The fastjet setup happens in run_pwg.py, so that indeed is an issue from standalone compiling.   
2.) Do we use all these processes in v2? E.g. I cannot find the corresponding cards or a sample that contains powheg and trijet.  This madlib error already appears in 7_1.

**Comment by agrohsje** [comment]
I tried HZJ in 9_2 and it compiles fine using 
https://raw.githubusercontent.com/cms-sw/genproductions/master/bin/Powheg/examples/V2/HZJ_Hee_NNPDF30_13TeV/HZJ_Hee_NNPDF30_13TeV.input ; 
9_3 is still running. Will let you know once I know more.

**Comment by agrohsje** [comment]
for the two processes tested so far (hzj and ggh with mass effects) I didn't have any trouble compiling the code nor producing a gridpack. However, I am facing a serious issue during event generation: some of the weitghts are zero and the process gets aborted. I already saw this feature two days ago, when testing single top tW. I assumed it is a problem with the new process but no it seems like this is a more general issue, hopefully related to the warning I mentioned above.
@perrozzi luca can you comment more on your findings? i would focus on the zero weight issue.

**Comment by perrozzi** [comment]
@agrohsje thanks a lot, I have prepared an automated script for testing this, I am running and I will let you know asap.
do you have the output of the crashing files? it is important to check, for instance, whether is a single PDF causing this or is a powheg problem

**Comment by yuanchao** [comment]
I also tested some of the processes with input card example available on CMSSW_9_3_0:
   * weakinos, Wbbj, Wbb_dec, ggHH, disquark --> (skipped as no input card)
   * trijet --> linking failed: missing libmadgraph (need to build manually?)
   * HZJ --> compiles and runs normal
   * gg_H --> linking failed: multiple definition in obj/pwhg_bookhist-multi.o

For trijet, probably just need some modification in the driving script to d/l and compile madgraph. But for gg_H, I don't know how to fix it.

**Comment by agrohsje** [comment]
@perrozzi  the problem appears also for scale re-weighting. i can reproduce it running in standalone mode. would it make sense, as an intermediate solution, to just skip events with 0.0 weights instead of killing the whole job? 
i am checking the powheg source. in case somebody wants to try it as well. please find input cards for hzj here:    http://www.desy.de/~agrohsje/hidden/powheg_zeroweight/ 
the problem can be checked by doing grep ">0.00000E+00</wgt>" pwgevents.lhe

**Comment by perrozzi** [comment]
Hi, so i implemented and used the script https://github.com/cms-sw/genproductions/blob/master/bin/Powheg/source/test_source_compilation.sh
The output is attached
[compile_report_-_powhegboxV2_rev3429_date20170726_-_slc6_amd64_gcc630_-_CMSSW_9_3_0.txt](https://github.com/cms-sw/genproductions/files/1317028/compile_report_-_powhegboxV2_rev3429_date20170726_-_slc6_amd64_gcc630_-_CMSSW_9_3_0.txt)
I used a single, random input card because I am only testing the compilation so far, and I believe only the PDF is important to fetch LHAPDF instead of the internal ones.

The failing processes in my case are still: bbH, dislepton-jet, gg_H, ggHH, HZJ, trijet, Wbb_dec, Wbbj, weakinos
I will try to understand why. In particular, I compile everything locally, using always the same base directory, but each compilation happens in a separate folder. I don't know if there is some "hysteresis" for previous compilations, but I would be suprised (will check).
I will also check the impact of using a "random" vs "real" datacard.

I would be good to send already now an email to HN asking which POWHEG processes are used in CMS, because I am not sure I have a complete list in my mind...
@agrohsje, @covarell or @yuanchao can you please do it?

@agrohsje I will look at the weights (other please do it as well)

**Comment by agrohsje** [comment]
just send an email to the hn.

**Comment by perrozzi** [comment]
Hi, I can confirm the null weights. Overall, 2% of the weights seem to be so.
However, they don't seem to be necessarily wrong. Also, it seems to be an effect of rounding. 
I can see weights ranging from 1e-10 to 1e+8.
We can also contact the authors, but I think this is something we have live with.
I would agree to remove the error message, just put it as a warning
@covarell @yuanchao

**Comment by agrohsje** [comment]
I found the source of the zero weights. The powheg code is perfectly fine, it is a feature of the nnpdfs. E.g.for c and b quarks they can be neg. and they are set to zero. If both of them are 0 for the underlying born, they are still zero for real corrections as just one of them gets replaced with a gluon. So if we change the fac scale, we can get neg. weights. 
@covarell @yuanchao should we ping the powheg authors about issues like the one above:
pwhg_cpHTO_reweight.f:864:19:

    res(5,1)= -1/2*(rz2**2-3.d0*rz4)
               1

Warning: Integer division truncated to constant '0' at (1) [-Winteger-division]

**Comment by perrozzi** [comment]
Updated **MG5_aMC@NLO** settings to CMSSW_7_1_30 (cfr [generation script](https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L47) )
Changing the title of the issue to be POWHEG specific at this point
