### ISSUE TITLE
[mg and LHEExternalProducer] Number of LHE events produced is lower than expected

### ISSUE THREAD

**Issue by perrozzi** [cms-sw/genproductions#1340]
According to this thread https://hypernews.cern.ch/HyperNews/CMS/get/prep-ops/4328/1/1.html
there are mg5_amc workflows that produce lhe files with lower number of events than what they are required to produce, and CMSSW expects to find.
The issue is not flagged with a custom error, so the exit code is not distinguishable from generator crashes, for instance. It seems to be process dependent, and random seed dependent, which makes it difficult to reproduce.
The current handling by computing is to patiently chase these cases and resubmit them, hoping that they will not fail again.

After talking to @vlimant a few action items/options can be foreseen to (try to) overcome this (according to my recollection, please correct me if something is not right):
- from the logs of the failed jobs, collect the distribution of the number of events actually produced
- it would be also interesting to see what is the fraction of jobs that is affected by this problem
- in case the jobs fail with very large number of events (for instance >10K) use the nevents passed as parameter to the job as a maximum number of events
- since mg5_amc@nlo doesn't crash but simply ends, control at the end of runcmsgrid.sh if 100% of the requested events has been produced, otherwise raise an exception with a **dedicated** error code. The jobs failing with this error code can be either resubmitted for a limited number of times (e.g. 5) or not resubmitted
- another possibility is to allow GS to create a lower number of events without raising an exception. This option should be evaluated carefully because could introduce unwanted consequences

Let me know if I missed something or you have other ideas.

We can plan another dedicated discussion in one of the following pre-MCCM meetings inviting representatives from computing
(@anorkus fyi)

**Comment by perrozzi** [comment]
In any case, we should contact the MG5_aMC@NLO authors and try to understand why this happens and ask to fix it in case is possible. 
AFAIK @bendavid sholud have a possible explanation

**Comment by kdlong** [comment]
@perrozzi do you have some examples of workflows this happens in? Is the runcmsgrid.sh script ever asked to produce more than ~500 events? This is a common issue when running MadGraph for complicated processes, but I've never seen it using a gridpack.

**Comment by bendavid** [comment]
This has been an issue since ever.  I was discussing this with Olivier recently, and it's possible it's been fixed in 2.6.x.  I'll double check the status.

**Comment by bendavid** [comment]
Olivier indeed already has a fix for this, but it wasn't included in 2.6.0 yet.
(probably it will be straightforward to produce a patch, at least on top of the 26x branch, if not also on 24x)

Btw, this issue only (ever) affects LO generation.

**Comment by perrozzi** [comment]
Thanks. It would be great to have such a patch in 24x asap if possible. We can write to Olivier if needed

**Comment by bendavid** [comment]
I'm not sure how reasonable it is for us to keep asking for patches to 2.4.x.  We should really try to move to 2.6.x ASAP.

Since we have lived with this issue for years, it is surely survivable for the beginning of the production.

**Comment by vlimant** [comment]
Hi josh, the argument goes both ways, it has create enough issue for ages that we need to stop the bleeding. I would find quite disrespectful the fact that there is actually a fix on the market, to prevent from wasting operation's time, and that we are not applying it.
So I am in favor of either retiring completely 2.4 from production within a month, or move in a patch in the same time scale.
All in favor to moving to a version that can be reasonably operated ; note such request are shooting 10s of thousands of jobs down the drain at the moment.

Can one of you guys make the patch/PR for 2.4 to help Olivier with ?

**Comment by bendavid** [comment]
Hi,
The patch is currently intertwined with another update, so there is not a clean patch available yet for neither 2.4.x or 2.6.x.  It is being actively discussed and will be added ASAP to whichever/both branches as soon as it becomes available.

**Comment by perrozzi** [comment]
any news on this?

**Comment by bendavid** [comment]
These changes are intertwined with the new feature being discuss and tested in the mail thread titled "Gridpack readonly"

Olivier was not intending to separate it out and make a separate patch, so the path to getting this fixed is tied to the convergence of that thread and the new readonly gridpack feature being discussed there.
