### ISSUE TITLE
is5FlavorScheme is undefined at this point when using cmsConnect

### ISSUE THREAD

**Issue by jfernan2** [cms-sw/genproductions#1347]
https://github.com/cms-sw/genproductions/blob/86ec71b7d19e00f9367b543b57615297d25af511/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L478

**Comment by qliphy** [comment]
"is5FlavorScheme" is defined here:   https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L350-L353

Not sure it is specially relate to CMSConnet,  maybe @khurtado @kdlong can have a check

**Comment by perrozzi** [comment]
it could be that there reason is that the grep only searches the last 20 lines. 
One should probably used instead:
`if more $LOGFILE | grep -q -e "^p *=.*b\~.*b" -e "^p *=.*b.*b\~"; then `
or similar

**Comment by kdlong** [comment]
Ah, I think it's because CMSConnect runs separately for the codegen and evtgen steps, and creates a separate log file for each. Will look into this and hopefully have a fix shortly.

**Comment by perrozzi** [comment]
@khurtado could you have a look at this by chance?

**Comment by khurtado** [comment]
@perozzi, I'm on parental leave until Oct 08, I can surely take a look at it when I'm back if this hasn't yet been resolved by then.

**Comment by perrozzi** [comment]
Happy parenting then :-)

**Comment by perrozzi** [comment]
@qliphy this has become the next most urgent issue to solve, may I kindly ask to see whether you can find a quick fix, based on the information above?

**Comment by kdlong** [comment]
@qliphy @perrozzi I should have a pull request in a few minutes, testing now

**Comment by kdlong** [comment]
Should be addressed with #1381
