### ISSUE TITLE
[upload of datacards] upload only example datacard and script to produce others

### ISSUE THREAD

**Issue by perrozzi** [cms-sw/genproductions#1350]
I am wondering whether we need to fill genproductions with hundreds (thousands) of datacards often differing by one number. This makes basically impossible any real check before merging the PR.
What about asking to upload, whenever possible, only one example datacard and the script to produce the others?
In the end we don't link genproductions, it's just for reference/check.

**Comment by kdlong** [comment]
I agree. We could also support some simple scripts to fill parameters in run cards if it's useful.

**Comment by perrozzi** [comment]
definitely!
