### ISSUE TITLE
[mg] remove proton and jet definitions from mg_amc proc cards

### ISSUE THREAD

**Issue by perrozzi** [cms-sw/genproductions#1359]
Because it is taken automatically from the model.
And the PDF handles it from the log.
The parsing script still checks for the proton and jet definitions. We could enforce not to specify it.

Also, the proton and jet definitions could be automatically stripped off in the import-from-pre2017 script

**Comment by perrozzi** [comment]
Hi, this is currently being enforced.
However I have a doubt: provided that we let mg5_amc handling tne number of flavors automatically, what happens to
`maxjetflavor    ! Maximum jet pdg code` ?
I remember vaguely something like "is not used anymore" but I don't remember in which version, can you please comment?

@bendavid @kdlong

**Comment by bendavid** [comment]
I believe this is also set automatically by madgraph if it is omitted from the run card (double checking now)

If this is the case then we should also make it a convention and/or enforce that it is omitted.

**Comment by bendavid** [comment]
Ok, the automatic setting of maxjetflavor doesn't seem to consistently work in 2.4.x at least, so I would suggest we keep setting this explicitly in the run card for now.

(but still no need to define the proton and jet definitions in the proc card, since this does work automatically)

**Comment by bendavid** [comment]
(the automatic handling which was added is such that when you generate the output directory, the default run card which is placed there has the correct maxjetflavor automatically set, but since we replace the run card with the one provided by the user, we don't profit from this.)

**Comment by perrozzi** [comment]
this sounds a bit risky because we are inviting the contacts not to care too much about the flavor scheme but then there is a parameter that they need to set.
I think it would make sense to ask to remove this parameter and patch it as we do for the pdf (unless there is a problem)

**Comment by bendavid** [comment]
But isn't it possible to have the scripts which check the cards still check this for consistency? (actually I thought they were already)

**Comment by perrozzi** [comment]
I am looking at the script and there might be a few things to improve... for instance this is not sufficient to retrieve the 5f or 4f...
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/Utilities/parsing_code/parsing.py#L54
anyway since this script is run before mg5_amc and we don't define proton and jet, I still think it can't work so we need to set maxjetflavor kind of here https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L351

**Comment by perrozzi** [comment]
@kdlong please consider also this in the forthcoming PR of "single place where to specify PDFs" for powheg and mg_amc

**Comment by perrozzi** [comment]
last item implemented in https://github.com/cms-sw/genproductions/pull/1409
