### ISSUE TITLE
Inverted logic for extra parameters in madgraph runcmsgrid scripts

### ISSUE THREAD

**Issue by bendavid** [cms-sw/genproductions#1365]
Looks like "-z" is used where "-n" should be, eg here
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/runcmsgrid_LO.sh#L15-L44
(and also in the NLO scripts)

**Comment by bendavid** [comment]
(And I think this will completely break the automated override of the environment.)

**Comment by perrozzi** [comment]
https://github.com/cms-sw/genproductions/pull/1366

**Comment by perrozzi** [comment]
thanks for spotting it, please crosscheck...
