### ISSUE TITLE
[mg] Request for upload of model file

### ISSUE THREAD

**Issue by AndreasAlbert** [cms-sw/genproductions#1512]
Hi, 
could you please upload this model file to the central page:

/afs/cern.ch/work/a/aalbert/public/share/2017-11-13_dmwg_model/Pseudoscalar_2HDM.tgz

It is the 2HDM + pseudoscalar model that is currently being studied in the LHC DMWG.

Thank you

Andreas

**Comment by perrozzi** [comment]
done

**Comment by AndreasAlbert** [comment]
Great, thanks!
