### ISSUE TITLE
Error in gridpack_generation.sh [pipe:  Operation not permitted]

### ISSUE THREAD

**Issue by gitytakahas** [cms-sw/genproductions#1517]
Dear gen expert, 

This line,

https://github.com/cms-sw/genproductions/blob/430731ad9eeb5e37794f1f150cdad4528c8273e4/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L105

seems not work if I do it in lxplus. Can you please check? 
(it might be just me ...)

**Comment by kdlong** [comment]
Yes, it seems that it doesn't work on afs. A quick/dirty fix could be to replace ${LOGFILE}.pipe in these few lines with

```fifofile=/tmp/${USER}/$(basename $LOGFILE).pipe```

**Comment by gitytakahas** [comment]
Thanks for your check & proposed modifications ! 
I guess it would be the best if you can fix this and update the master branch so that everybody can profit from it?

**Comment by perrozzi** [comment]
what is the status for this?
