### ISSUE TITLE
Cross section 0.0 before and after matching for madgraph gridpack

### ISSUE THREAD

**Issue by deepakcern** [cms-sw/genproductions#1522]
Hi,
I have found an issue with GenXanalyser with madgraph gridpack, reported at:
https://hypernews.cern.ch/HyperNews/CMS/get/generators/3707.html

I get zero cross section before and after the matching, however, i see events in LHE.
Could you please have a look into the issue?

Thanks,
Deepak (BTV MC contact)

**Comment by efeyazgan** [comment]
This may simply be due to the wrong name in your config (i.e. pythia8P5Settings --> pythia8CP5Settings).
