### ISSUE TITLE
cmsconnect job days when decaying events

### ISSUE THREAD

**Issue by agrohsje** [cms-sw/genproductions#1524]
Dear all, dear @khurtado @kdlong 

I am running gridpacks with 5.2.4 using the 2HDMA UFO for ttbar chi chi~ at NLO. I can run gridpack production locally and it just works fine using these cards  [1]. When I run at DESY batch, my jobs get killed because of high mem usage (>32 GB) which I cannot see when monitoring locally. I already checked with Olivier and he confirmed my findings. Assuming that it is a DESY batch issue, I moved to  cmsconnect, and indeed it runs fine [2] up to the point where madspin should decay the events [3]. 
The job just stops after printing: 
INFO: MadSpin: Decaying Events 
INFO:   
INFO: Decaying the events...  

If I count the time properly, I would say the job was running 8 hours and then nothing happened until the 24 hours limit was hit. Is there something I am missing? Any hint on how to debug it would be great. Maybe there is something in the logs that I didn't spot. 

Cheers, Alexander.

[1] http://www.desy.de/~agrohsje/hidden/2hdma/comsconnect
[2] http://www.desy.de/~agrohsje/hidden/2hdma/comsconnect/ttbarDM__Pseudoscalar_2HDM__ma_20_mA_600_mH_600_mHc_600_mchi_10_tanbeta_0.3_gSM_1_gDM_1_codegen.log
[3] http://www.desy.de/~agrohsje/hidden/2hdma/comsconnect/nohup.out

**Comment by kdlong** [comment]
Hi Alexander,

I don't know why this happens. I would guess it's either an issue with MadSpin or a mistake in the gridpack_generation.sh script logic somewhere, but I'm not sure specifically. The easiest way to debug might be to rerun the gridpack with:

- removing the MadSpin card (so MadSpin isn't run)
- Commenting out this line: https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L718

If everything works up to this point, we should be able to have the gridpack with all the fortran files still stored so that debugging locally will be easier.

**Comment by agrohsje** [comment]
Mea culpa. In fact, there seems to be a problem with madspin. As he gridpack size didn't look too small I thought jobs that finished are fine but apparently that was naive.
 Running in 5.2.6 interactively, I see that the job hangs with the same last message as above:
INFO: MadSpin: Decaying Events
INFO:
INFO: Decaying the events...
and doing top I get this command running since about 12 hours:
713:38.78     check 
Kenneth do you have an idea of how to debug it or should I directly check with the authors?

**Comment by kdlong** [comment]
If you hit Ctrl+C do you get a traceback to the spot in the python code where the code is stuck? I think it will ultimately need to go to the authors but if it's possible to point them to where the problem comes from it can make the process faster.

**Comment by agrohsje** [comment]
Thanks Kenneth. Can I run madspin in nlo mode standalone as for LO? Just asking because we treat this differently in the gridpack_generation.sh.

**Comment by kdlong** [comment]
By NLO mode, you mean that the process was generated at NLO? I think MadSpin should always just be calculating decays at LO regardless of what the initial process was, so you should be able to run over an LHE file in pretty much the same way for both.

**Comment by agrohsje** [comment]
Yes NLO up to the decay. So there should indeed be no difference to Powheg + Madspin. Just wondering if there is something technically that I am missing. I will give it a try and send feedback one I know more from the authors. I will close the thread.
