### ISSUE TITLE
Issues with Sherpa "Decay" parameter

### ISSUE THREAD

**Issue by gomber** [cms-sw/genproductions#1526]
Dear All, 

I am facing some issues while generating the data cards for Z(jj)gamma process using Sherpa 2.1.1 generator.

My data card works perfectly fine, if I simply state the process as 
93 93 -> 93 93 22

But then I wanted to specify that Z decays to (jj), in order to do that I did the following:

Process 93 93 -> 23[a] 22;                                                                                                                                                 
Decay 23[a] -> 93 93;      

But with this change, the sherpa commands exits with the error(*)
I believe there is something wrong in the way I am defining the decay process or may be I need to change more in the run card for the same.

My main question is how to specify the Decay process in sherpa 2.1.1 generator?

Here is my run card which I am using :
(run){                                                                                                                                                                      
 EVENTS 1M; ERROR 0.1;                                                                                                                                                      
 MASSIVE_PS 4 5;                                                                                                                                                            
 FSF:=1.; RSF:=1.; QSF:=1.;                                                                                                                                                 
 SCALES STRICT_METS{FSF*MU_F2}{RSF*MU_R2}{QSF*MU_Q2};                                                                                                                       
 NJET:=2; LJET:=3,4; QCUT:=20.;                                                                                                                                             
 ME_SIGNAL_GENERATOR Amegic;                                                                                                                                                
 EVENT_GENERATION_MODE Unweighted;                                                                                                                                          
 MASSIVE[15] 1;                                                                                                                                                             
 BEAM_1 2212; BEAM_ENERGY_1 6500.;                                                                                                                                          
 BEAM_2 2212; BEAM_ENERGY_2 6500.;                                                                                                                                          
 MODEL SM+AGC;                                                                                                                                                              
 H3_GAMMA ${h3};                                                                                                                                                            
 H4_GAMMA ${h4};                                                                                                                                                            
 UNITARIZATION_SCALE 100000;                                                                                                                                                
 UNITARIZATION_N 2;                                                                                                                                                         
 UNITARIZATION_M 1;                                                                                                                                                         
}(run)                                                                                                                                                                      
(processes){                                                                                                                                                                
 Process 93 93 -> 23[a] 22;                                                                                                                                                 
 Decay 23[a] -> 93 93;                                                                                                                                                      
 Order_EW 3; CKKW sqr(QCUT/E_CMS);                                                                                                                                          
}(processes)                                                                                                                                                                
(selector){                                                                                                                                                                 
 ET 22 150. 13000.;                                                                                                                                                         
}(selector)                                                                                                                                                                 
EOF    

And my script is present here at lxplus, in case u want to reproduce the problem.
~gomber/public/Runjobs_Zjjgamma_Zgg.csh

Thanks & Regards
Bhawna Gomber
 (*)

ME_Generator_Base::SetPSMasses(): Massive PS flavours for Amegic: (c,cb,b,bb,t,tb,e-,e+,nu_e,nu_eb,mu-,mu+,nu_mu,nu_mub,tau-,tau+,nu_tau,nu_taub,Z,W+,W-,h0)
Amegic::Initialize(): Set gauge 1.
Matrix_Element_Handler::BuildProcesses(): Looking for processes Matrix_Element_Handler::BuildSingleProcessList(): Error in initialising ISR (P+ -> e-) x (P+ -> e+). Ignoring process.
 done ( 316 MB, 0s / 0s ).
----- Begin Fatal Exception 09-Nov-2017 04:25:47 CST-----------------------
An exception of category 'Unknown' occurred while
   [0] Processing run: 1 luminosityBlock: 1
   [1] Calling beginLuminosityBlock for unscheduled module SherpaGeneratorFilter/'generator'
Exception Message:
An exception of unknown type was thrown.
----- End Fatal Exception -------------------------------------------------

Exception_Handler::SignalHandler: Signal (11) caught. 
Exception_Handler::GenerateStackTrace(..): Generating stack trace 
{
  0x7fe180fb4d14  in 'SHERPA::Event_Handler::TotalXS()' (Event_Handler.C:497)
  0x7fe189ba73f0  in 'SherpaHadronizer::statistics()' (??:?)
  0x7fe189babe57  in 'edm::GeneratorFilter<SherpaHadronizer, gen::ExternalDecayDriver>::endRunProduce(edm::Run&, edm::EventSetup const&)' (??:?)
  0x7fe1a0496c47  in 'edm::one::EDFilterBase::doEndRun(edm::RunPrincipal&, edm::EventSetup const&, edm::ModuleCallingContext const*)' (??:?)
  0x7fe1a0490640  in 'edm::WorkerT<edm::one::EDFilterBase>::implDoEnd(edm::RunPrincipal&, edm::EventSetup const&, edm::ModuleCallingContext const*)' (??:?)
  0x7fe1a03e5253  in 'decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::doWork<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::MyPrincipal&, edm::EventSetup const&, edm::CPUTimer*, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::Context const*)::{lambda()#1}>(bool edm::Worker::doWork<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::MyPrincipal&, edm::EventSetup const&, edm::CPUTimer*, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::Context const*)::{lambda()#1})' (??:?)
  0x7fe1a03e54cb  in 'bool edm::Worker::doWork<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::MyPrincipal&, edm::EventSetup const&, edm::CPUTimer*, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::Context const*)' (??:?)
  0x7fe1a03e5688  in 'void edm::GlobalSchedule::runNow<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::MyPrincipal&, edm::EventSetup const&, edm::GlobalContext const*)' (??:?)
  0x7fe1a03e586a  in 'decltype ({parm#1}()) edm::convertException::wrap<void edm::GlobalSchedule::processOneGlobal<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}>(void edm::GlobalSchedule::processOneGlobal<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1})' (??:?)
  0x7fe1a03eba24  in 'void edm::GlobalSchedule::processOneGlobal<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::MyPrincipal&, edm::EventSetup const&, bool)' (??:?)
  0x7fe1a03dc9c1  in 'edm::EventProcessor::endRun(statemachine::Run const&, bool)' (??:?)
  0x7fe1a03bdabc  in 'statemachine::HandleRuns::endRun(statemachine::Run const&, bool)' (??:?)
  0x7fe1a03bdb6c  in 'statemachine::HandleRuns::finalizeRun(bool)' (??:?)
  0x7fe1a03be6ea  in 'statemachine::HandleRuns::~HandleRuns()' (??:?)
  0x7fe1a03be789  in 'statemachine::HandleRuns::~HandleRuns()' (??:?)
  0x7fe1a03dbe8d  in 'edm::EventProcessor::runToCompletion()' (??:?)
  0x40a35f        in 'main' 
}   Cannot continue.
Exception_Handler::GenerateStackTrace(..): Generating stack trace 
{
  0x7fe180fb4d14  in 'SHERPA::Event_Handler::TotalXS()' (Event_Handler.C:497)
  0x7fe189ba73f0  in 'SherpaHadronizer::statistics()' (??:?)
  0x7fe189babe57  in 'edm::GeneratorFilter<SherpaHadronizer, gen::ExternalDecayDriver>::endRunProduce(edm::Run&, edm::EventSetup const&)' (??:?)
  0x7fe1a0496c47  in 'edm::one::EDFilterBase::doEndRun(edm::RunPrincipal&, edm::EventSetup const&, edm::ModuleCallingContext const*)' (??:?)
  0x7fe1a0490640  in 'edm::WorkerT<edm::one::EDFilterBase>::implDoEnd(edm::RunPrincipal&, edm::EventSetup const&, edm::ModuleCallingContext const*)' (??:?)
  0x7fe1a03e5253  in 'decltype ({parm#1}()) edm::convertException::wrap<bool edm::Worker::doWork<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::MyPrincipal&, edm::EventSetup const&, edm::CPUTimer*, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::Context const*)::{lambda()#1}>(bool edm::Worker::doWork<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::MyPrincipal&, edm::EventSetup const&, edm::CPUTimer*, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::Context const*)::{lambda()#1})' (??:?)
  0x7fe1a03e54cb  in 'bool edm::Worker::doWork<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::MyPrincipal&, edm::EventSetup const&, edm::CPUTimer*, edm::StreamID, edm::ParentContext const&, edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::Context const*)' (??:?)
  0x7fe1a03e5688  in 'void edm::GlobalSchedule::runNow<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::MyPrincipal&, edm::EventSetup const&, edm::GlobalContext const*)' (??:?)
  0x7fe1a03e586a  in 'decltype ({parm#1}()) edm::convertException::wrap<void edm::GlobalSchedule::processOneGlobal<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1}>(void edm::GlobalSchedule::processOneGlobal<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::MyPrincipal&, edm::EventSetup const&, bool)::{lambda()#1})' (??:?)
  0x7fe1a03eba24  in 'void edm::GlobalSchedule::processOneGlobal<edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3> >(edm::OccurrenceTraits<edm::RunPrincipal, (edm::BranchActionType)3>::MyPrincipal&, edm::EventSetup const&, bool)' (??:?)
  0x7fe1a03dc9c1  in 'edm::EventProcessor::endRun(statemachine::Run const&, bool)' (??:?)
  0x7fe1a03bdabc  in 'statemachine::HandleRuns::endRun(statemachine::Run const&, bool)' (??:?)
  0x7fe1a03bdb6c  in 'statemachine::HandleRuns::finalizeRun(bool)' (??:?)
  0x7fe1a03be6ea  in 'statemachine::HandleRuns::~HandleRuns()' (??:?)
  0x7fe1a03be789  in 'statemachine::HandleRuns::~HandleRuns()' (??:?)
  0x7fe1a03dbe8d  in 'edm::EventProcessor::runToCompletion()' (??:?)
  0x40a35f        in 'main' 
}
Exception_Handler::Terminate(): Pre-crash status saved to '/uscms_data/d3/bhawna/newarea/Sherpa_13TeV/Cards_production/Zllgamma_Zgg/CMSSW_7_1_20/src/MY/PROJECT/test/Status__Thu_Nov__9_04-25-48_2017'.
------------------------------------------------------------------------
Please cite the publications listed in 'Sherpa_References.tex'.
  Extract the bibtex list by running 'get_bibtex Sherpa_References.tex'
  or email the file to 'slaclib2@slac.stanford.edu', subject 'generate'.

**Comment by kdlong** [comment]
Can you try using ```Decay 23[a] -> 93 93;```? I'm not sure if this is the issue, but this container should be only the quarks and not the gluons. 

As an aside, in CMSSW_9_3_X the version of Sherpa should be 2.2.4.

**Comment by gomber** [comment]
@kdlong thanks for the suggestion, but still the same issue.

And I am using CMSSW_7_1_20 as discussed sometime back to prepare the sherpa gridpacks.

**Comment by kdlong** [comment]
Ah right, these are for 2016. @vciulli @pmillet any ideas?

**Comment by pmillet** [comment]
I dont have an idea right away but would suggest to rerun Sherpa standalone with -f RunCardName.dat (exectuable is located in sherpa bindir, see 'scram tool info sherpa' output), and then write to the Sherpa mailing list attaching the Runcard and the error message.
