### ISSUE TITLE
[MG] LSF jobs create unwanted output directories

### ISSUE THREAD

**Issue by AndreasAlbert** [cms-sw/genproductions#1532]
Hi,

I am trying to run gridpack_generation on lxbatch LSF. I observe that all of the sub-jobs submitted by MG5 attempt to create output directories in my AFS home (like ~/LSFJOB_121215087). Is there a good way to prevent this?

The issue with this - apart from being annoying -  is that it causes AFS timeouts when running many jobs at once. Apparently single AFS volumes do not deal well with large numbers of concurrent accesses/writes. This sometimes causes the main gridpack jobs to fail and showers my inbox with LSF error messages (see below).

Any hints would be appreciated.

Thanks

Andreas

Host b603b6b16e.cern.ch - User aalbert - Job 121212122 ()
Cannot create directory /pool/lsf/aalbert/121201950/Pseudoscalar2DHM_MonoZLL_mScan_5F_mh3-200_mh4-300/Pseudoscalar2DHM_MonoZLL_mScan_5F_mh3-200_mh4-300_gridpack/work/processtmp/SubProcesses/P0_gg_xdxdxll/LSFJOB_121212122
Connection timed out

**Comment by perrozzi** [comment]
Hi @AndreasAlber I tried to search for such an option many times without success...
I tried now browsing this page
https://www.ibm.com/support/knowledgecenter/en/SSETD4_9.1.2/lsf_command_ref/bsub.1.html
and maybe I found a trivial way:
bsub -o /dev/null script.sh
let me know if it works

**Comment by perrozzi** [comment]
btw, in this way you will not get any information at all from the job. However (hopefully) you should get the usual gridpack logs for debugging purpose.

**Comment by AndreasAlbert** [comment]
Hi @perrozzi, thanks for the advice. I have added it to the patches of my local repository by modifying the lines at [1]. I will report back after testing.

https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/patches/0005-add-rsync-based-submit2-functionality-for-lsf-plus-v.patch#L276

**Comment by AndreasAlbert** [comment]
I added a [simple patch](https://cernbox.cern.ch/index.php/s/cEYBWiZMZ9fgAdd) in order to make cluster.py use "-o /dev/null" for submission. However, this makes the sub jobs fail (the main job cannot find results.dat, see [log](https://cernbox.cern.ch/index.php/s/yy0fsCeRrfy2UXE) ). Probably the way bsub implements this screws with some shell redirection inside the jobs.

@bendavid since you originally implement a good chunk of that code: Any ideas?

**Comment by AndreasAlbert** [comment]
I asked LSF support about this and in short, the answer is: there is no way to do this.
They suggest to instead use HTCondor.

**Comment by perrozzi** [comment]
if you get the chance to talk again with the LSF support, maybe tell them that is crazy not to have a way to do it...

**Comment by wajidalikhan** [comment]
Hi @AndreasAlbert , @perrozzi , 
Any luck with the problem you mentioned above Andreas Albert? Its really annoying and causing lots of main jobs to fail and sub-jobs submitted by MG5 resulting in failing to create sub-directories, and it gets horrible if one is trying to test 10-20 grid packs in one go, thousands of emails like these.

**Comment by bendavid** [comment]
No I never found a solution to this.  Yes it is horrible/crazy.
