### ISSUE TITLE
[MG] CMS Connect jobs: subjobs fail

### ISSUE THREAD

**Issue by AndreasAlbert** [cms-sw/genproductions#1534]
Hi,

I am trying to create some gridpacks with CMS Connect. Relevant info (cards, etc) below.
The short summary is that I can successfully run these cards locally or on LSF, but not on CMS Connect.

The generation ultimately fails because one or two of the subjobs fail and the main job cannot read the results.dat (log at [1]). Looking at the corresponding subprocess log [2], there are a lot of "Error done early" lines in it that do not appear in succesful subprocesses. Seeing how the production works on other architectures, I think there is a configuration problem somewhere (possibly Madloop?).

I have no idea at all how to debug this. Could anyone advise what to look at?

Best

Andreas

Cards in my  [my genproductions fork](https://github.com/AndreasAlbert/genproductions/tree/monoz_2hdm_production_clean_oct30/bin/MadGraph5_aMCatNLO/cards/production/2017/2HDM_5F/Pseudoscalar2DHM_MonoZLL_mScan_5F_mh3-200_mh4-500)

Submission command is

`name="Pseudoscalar2DHM_MonoZLL_mScan_5F_mh3-200_mh4-500"; nohup ./submit_cmsconnect_gridpack_generation.sh ${name} ./cards/production/2017/2HDM_5F/${name} > ${name}.debug 2>&1 &`

[1]` /afs/cern.ch/work/a/aalbert/public/2017-11-20_cmsConnect/Pseudoscalar2DHM_MonoZLL_mScan_5F_mh3-200_mh4-500.debug`
(error appears around line ~900)

[2]` /afs/cern.ch/work/a/aalbert/public/2017-11-20_cmsConnect/Pseudoscalar2DHM_MonoZLL_mScan_5F_mh3-200_mh4-500/Pseudoscalar2DHM_MonoZLL_mScan_5F_mh3-200_mh4-500_gridpack/work/gridpack/process/madevent/SubProcesses/P0_gg_xdxdxll/G2.26_1/run1_app.log`

**Comment by kdlong** [comment]
Hi Andreas,

I agree that the error seems to come from these couple of failed subprocesses. However, I have no idea how to interpret all the ```Error done early``` messages. Could you post this message to the MadGraph launchpad to ask the authors? Without any indication of what could cause this I don't know how to debug it as a CMSConnect issue.

**Comment by AndreasAlbert** [comment]
Hi Kenneth,

I suspected that this would be a launchpad-case, but wanted to ensure that we do not already know the answer to this. I will ask the MG5 authors.

Thanks

A

**Comment by AndreasAlbert** [comment]
Okay, posted on [launchpad](https://answers.launchpad.net/mg5amcnlo/+question/660943). According to Olivier, this is a file system issue (volume or quota full). If I read [gridpack_generation](https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L368) right, everything seems to be set to write to wherever you submit from (/local-scratch/aalbert/... in my case).
Since /local-scratch is neither full nor has any quotas, I am not sure what the problem is.
I will rerun to see if it's a temporary problem.

**Comment by kdlong** [comment]
@khurtado any suggestions on how to find more info related to this from CMSConnect logs?

**Comment by khurtado** [comment]
@kdlong, @AndreasAlbert :
I think there are 2 potential issues here.
- First, the madgraph job apparently  tries to write to `/tmp` in the worker node rather than using the condor scratch area. Most worker nodes do have some `/tmp`, but writing to it might be restricted depending on the site cluster configuration.
```
At line 174 of file driver.f (unit = 27, file = '/tmp/gfortrantmplgAYpZ')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE
```
- Second, the fortran code didn't recognize this as an issue and exits with ExitCode 0. So, the master thinks the job ran successfully (no jobs from @AndreasAlbert in condor_history associated to that process have a different ExitCode) and it doesn't try to resubmit.

Olivier mentions:
```
If that volume is too small please set the compiler flag to ask to write temporary file to another volume.
```
Do you guys know where that flag is? In general, condor jobs should always rely on its own scratch space and not `/tmp` areas.

**Comment by kdlong** [comment]
@khurtado: I don't know. I'll post a follow up to Olivier asking about it.

**Comment by AndreasAlbert** [comment]
@khurtado I am currently running a test with your suggestion. So far, I have not seen the same error as before, but I get subjobs failing because: 
>../madevent: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory

I do not think I can tell from the files I have what site that subjob ran on.
Again, MG does not seem to recognize that this sub job fails. It tries to read the `result.dat` and fails.

**Comment by khurtado** [comment]
@AndreasAlbert : Thanks, I think I found the issue. I put up a quick fix

**Comment by khurtado** [comment]
@AndreasAlbert : Can you test PR #1541 ? I made a quick patch but haven't been able to test.
@kdlong: Could you also take a look at the patch?  Particularly, there is a loop in `survey.sh`, so I'm adding the exit $statuscode after line 82 here:

 https://github.com/khurtado/MadGraph5_aMC-NLO/blob/master/Template/LO/SubProcesses/survey.sh#L82

**Comment by kdlong** [comment]
Thanks @khurtado @AndreasAlbert. So this looks like something that should be fixed in MadGraph, right? I guess this should this also fix the incorrect return code for the previous error?

@khurtado: do you know how this libgortran error happens? I would have thought that all the compiler architecture came from cvmfs and therefore this type of configuration problem couldn't happen.

You can also see that Olivier added an additional comment about the compiler flags he's talking about. It seems that these tmp file are created by gfortran itself, which seems like it might be site specific.

**Comment by AndreasAlbert** [comment]
@khurtado Will do. If I understand correctly, this only fixes condor not getting the right exit codes. If your fix works, we will resubmit the failing jobs until they work out. This does not solve the jobs writing to /tmp/, right?

According to the [documentation linked by Olivier](https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vnaf/index.html), it seems that fortran looks at the "TMPDIR" environment variable to see where to write scratch files. We can modify what is passed for that variable in cluster.py.

**Comment by kdlong** [comment]
Good point @AndreasAlbert, maybe it's not so awful as I feared. Could you try patching the same file as Kenyi just did (/Template/LO/SubProcesses/survey.sh) to unset this environment variable?

**Comment by AndreasAlbert** [comment]
@kdlong I am not sure unsetting it will do the trick. Depending on [what documentation](https://gcc.gnu.org/onlinedocs/gcc-5.1.0/gfortran/TMPDIR.html) you read, it seems like /tmp is the fall-back if TMPDIR is not set.

I was thinking to explicitly pass TMPDIR="." via condor_submit. [Patch here](https://gist.github.com/AndreasAlbert/b3e64c9c2e2e41f13f32cfc10699a787), currently testing. Maybe modifying survey.sh is easier, though.

**Comment by kdlong** [comment]
Agreed that this solution looks better

**Comment by khurtado** [comment]
@AndreasAlbert : Yes, the PR only solves the error propagation issue, not the `/tmp` problem itself.
@kdlong : The CVMFS mounting points can sometimes fail for different reasons (e.g the squid server in the site gets overloaded or has network issues), so I would just assume this was a transient error with one of the worker nodes.

Regarding TMPDIR, the environment in the batch jobs won't make TMPDIR point to an unwritable path, so this is most likely fortran finding the variable unset already and falling back to `/tmp`.

If @AndreasAlbert patch test fails. I would make  `TMPDIR` point to `_CONDOR_SCRATCH_DIR` and keep the fallback to `/tmp`.

So, something like
```
export TMPDIR=${TMPDIR:-${_CONDOR_SCRATCH_DIR:-/tmp}}
```
in `survey.sh` should do the trick for that. Although, patching all template files like in [1] might be needed to be safer.

[1] https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/patches/0010-fix-singularity-ld-library-path.patch

**Comment by AndreasAlbert** [comment]
@khurtado I tested my fix. Does not work. Will try yours tomorrow.

**Comment by khurtado** [comment]
@AndreasAlbert : Sounds good. I updated my patch in #1544 to include a fix for TMPDIR in the worker nodes environment.

**Comment by AndreasAlbert** [comment]
@khurtado: The gridpack that previously failed now works after including your fix. Assuming a semi-stochastic nature of the /tmp problem, that is not definite proof of anything, of course.

**Comment by perrozzi** [comment]
in the meanwhile PR merged, as at least it doesn't seem to harm and likely solves the problem

**Comment by khurtado** [comment]
@AndreasAlbert Thanks for the feedback! 
Considering changes have been merged and this likely solves the problem, I propose we close the issue but reopen if you happen to see the same error message again.

**Comment by AndreasAlbert** [comment]
@khurtado Agreed. Thanks to you for helping out!
