### ISSUE TITLE
[MG] cannot generate DY HT LO samples

### ISSUE THREAD

**Issue by aspiezia** [cms-sw/genproductions#1536]
Dear All,
I am having troubles in generating the DY HT LO samples. If I run on lxplus or with CMS connect, I have different errors but in both cases I am not able to have the final gridpacks. I only managed to succefully generate the 100to200 bin. I have put the cards, the lxplus and the CMS connect outputs here:
/eos/cms/store/group/phys_generator/tests/Aniello_DYProblem/

Thanks,
Aniello

**Comment by kdlong** [comment]
For the LSF issue, there is really nothing to do other than try again, since the problem comes from the large load that jobs place on afs. This is one of the main reasons we've made a push to use other submission types.

For the CMSConnect issue, I think we've started to understand where these failures are coming from, as you can see in the discussion in #1534. You can try the suggestion Kenyi made, and/or you can wait until we work out a more permanent solution with the authors.

**Comment by aspiezia** [comment]
Dear Kenneth, I have resubmitted again on lxplus without success. And I have also followed the suggestion from Kenyi for CMS Connect, and also in this case I have always the same error.

**Comment by efeyazgan** [comment]
Can you also share /afs/cern.ch/work/a/aspiezia/GenContact/DY/genproductions/bin/MadGraph5_aMCatNLO/gridpack_generation.sh

**Comment by aspiezia** [comment]
Hi, you can find it here:
/afs/cern.ch/work/a/aspiezia/public/4Generation/gridpack_generation.sh

**Comment by efeyazgan** [comment]
Isn't this part wrong elif is outside an "if loop"):
----
elif [ "${jobstep}" = "INTEGRATE" ] || [ "${jobstep}" = "ALL" ]; then  
  echo "Reusing existing directory assuming generated code already exists"
  echo "WARNING: If you changed the process card you need to clean the folder and run from scratch"
----
And there is a "fi" in line 450 which has no "if" somewhere before?

I wish this was in python. I will try to see once again what I claimed above is true.

**Comment by efeyazgan** [comment]
I take it back - the if/fi's seem correct.

**Comment by aspiezia** [comment]
Hi Efe, I did not change anything in the gridpack_generation.sh file.

**Comment by qliphy** [comment]
@aspiezia   With your cards (HT-600to800), I could get the gridpack out [1] after one day's run with Condor submission at LPC.  So I think there is no problem related to cards/scripts and MG itself.   You may try again with other submissions, notice CMS Connect has made some fixes recently so it may work now: https://github.com/cms-sw/genproductions/pull/1544

[1] /eos/cms/store/user/qili/gridpacks/DYJets_HT-600to800/

**Comment by aspiezia** [comment]
Dear Qiang, it is great that you can generate the gridpacks. I have tried again, after the fix here: https://github.com/cms-sw/genproductions/pull/1544
but the production failed again. I have tried also again on lxplus setting both the queues to 2nw, but also in this case the production failed. You can find all the outputs here:
/afs/cern.ch/work/a/aspiezia/public/4Generation/GridPacksFailed/

I am not sure if I can run on LPC. Can I? For my understanding I can run only on lxplus and CMS Connect and for both I am unable to obtain the gridpacks.

**Comment by efeyazgan** [comment]
You can first try condor at CERN and if not you can get an LPC account if needed.

**Comment by kdlong** [comment]
Condor at CERN isn't working currently. 

We think we're making progress with the issues affecting CMSConnect. I also don't know what the requirements for LPC accounts are. In the meantime can you appeal to other Higgs contacts or analyzers to help? Access to a condor cluster at a T2 would be your best best. With the cards in place, it's just a matter of running a command.

**Comment by khurtado** [comment]
@aspiezia : You seem to be running from `/stash`. Could you try again but submitting from `local-scratch`? Stash hasn't been stable for a while and OSG is still debugging, which is why `local-scratch` was recommended for producing gridpacks.

https://hypernews.cern.ch/HyperNews/CMS/get/generators/3713.html

**Comment by aspiezia** [comment]
Hi Kenyi, thanks a lot. Using the local-scratch area solved the problem. I am starting to have the first gridpacks.

**Comment by khurtado** [comment]
@aspiezia Great! Good to know, thanks for reporting!

**Comment by khurtado** [comment]
I think this issue can be closed.
