### ISSUE TITLE
Issues with CODEGEN step in MG26x branch

### ISSUE THREAD

**Issue by khurtado** [cms-sw/genproductions#1586]
The usage of the function make_gridpack() in the gridpack_generation scripts is executed through a pipe (via tee) when not executed interactively.

https://github.com/cms-sw/genproductions/blob/mg26x/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L698

This creates a sub-shell, which conflicts with lines in the function that try to exit the main shell, like when only the CODEGEN step wants to be executed. I.e:  [HERE](https://github.com/cms-sw/genproductions/blob/mg26x/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L284), we should just exit gridpack_generation.sh, but it will only exit make_gridpack() and move to the next lines in the script, which will produce an error.

**Comment by khurtado** [comment]
I put a fix on #1587 and tested it on wplus_4f_NLO. The PR includes more than just this fix though (all the latest CMS-Connect related changes applied to the main branch)

**Comment by perrozzi** [comment]
can this issue be closed?

**Comment by khurtado** [comment]
Yes it can! I will go ahead and do so since I was the one creating the issue.
