### ISSUE TITLE
cmsconnect: IOError : [Fail 30 times]

### ISSUE THREAD

**Issue by cmantill** [cms-sw/genproductions#1599]
Hi @khurtado 

I'm trying to reproduce a gridpack of ZJets at LO using cmsconnect, up to 4j with these cards:
https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/ZJets_LO_MLM/ZJetsToQQ_HT600to800/ZJetsToQQ_HT600to800_proc_card.dat

But the jobs seem to be taking too long and 3 of them are never finished. I use the following command:
`nohup ./submit_cmsconnect_gridpack_generation.sh ZJetsToQQ_HT600to800 cards/production/2017/13TeV/ZJets_LO_MLM/ZJetsToQQ_HT600to800/ 1 "4 Gb" > mysubmit_ZJetsToQQ_HT600to800.debug 2>&1`

[Here is the log](http://cmantill.web.cern.ch/cmantill/ZJets4j.log)

And the other files can be found here:
/local-scratch/cmantill/genproductions/bin/MadGraph5_aMCatNLO/600to800upt04j

I resubmitted it, but not sure if there is a fix I can implement or another command that could allow these jobs to finish.

Thanks,

Cristina

**Comment by khurtado** [comment]
@cmantill : Did that happen to fail on the weekend? There was a huge load coming from a user submitting to stash on the weekend. I fixed that but I need to restrict submission to that area by force to prevent that from happening again.

Madgraph jobs are not always uniform in terms of runtime. Some take really short and some can take days, depending on the gridpack process and its complexity. The 3 jobs you mentioned ran for over 16 hours and were evicted, so they ran again requesting at least 36 hours to run, but the schedd issue stopped the production before they were able to finish, so I don't think there is anything wrong with those jobs in particular or the worker nodes that were running them, it's just the way madgraph does things.

**Comment by cmantill** [comment]
@khurtado ok thanks a lot for the explanation! indeed I expect the jobs to take long, I'll try resubmitting then and will close this issue after.

Thanks,

Cristina
