### ISSUE TITLE
Repository "Collaborators and teams"

### ISSUE THREAD

**Issue by perrozzi** [cms-sw/genproductions#1604]
@smuzaffar @davidlange6  we should clarify the situation concerning the "Collaborators and teams".

Currently 2 teams are granted access to this repository:
   * **cms-sw-writers** (2 members, write access) which I have no idea of, I can imagine are the 2 of you
   * **generators-l2** (4 members,  admin access) which ONLY contains FORMER GEN L2, neither Efe nor me

Efe and I are added as users with admin access.

Who controls generators-l2 ? Can it be updated? Isn't more efficient to handle things on user basis for the L2, other than a team which apparently easily gets outdated?

**Comment by smuzaffar** [comment]
@perrozzi , we control the teams via cms-bot (https://github.com/cms-sw/cms-bot/blob/master/gh-teams.py)
- cms-sw-writers:  This team consists for cmssdt members who can take action if cms-sw owners (david L., myself and couple of others are away) https://github.com/cms-sw/cms-bot/blob/master/gh-teams.py#L12
- generators-l2: Team member of this are mentioned here https://github.com/cms-sw/cms-bot/blob/master/gh-teams.py#L47 , please propose change to it

**Comment by perrozzi** [comment]
thanks a lot, PR done
