### ISSUE TITLE
[CMSConnect] Temporary directory creation in /stash/user/... fails

### ISSUE THREAD

**Issue by AndreasAlbert** [cms-sw/genproductions#1623]
The CMSConnect gridpack submission script attempts to create a temporary directory under `/stash/user/...` [1], which does not seem to exist anymore. This seems to have been the case for at least a few of days now. @khurtado: will `/stash/user` come back soon or do we need to change the script?

[1] https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/submit_cmsconnect_gridpack_generation.sh#L195

**Comment by khurtado** [comment]
@AndreasAlbert Thanks for the catch! There was a security-related reboot a couple of days ago and it seems stash didn't get mounted after that.... I just fixed that. Let me know if you still see issues.

**Comment by AndreasAlbert** [comment]
@khurtado I can see it working again. Thank you!

**Comment by gourangakole** [comment]
Hi @khurtado does that means ...the gridpack creation jobs submited in the meantime should kill and resubmit again. 
for example in my log I see that.
/local-scratch/gkole/3rdJan2018/genproductions/bin/MadGraph5_aMCatNLO/mysubmit_vh012j_5f_NLO_FXFX_M123_VToAll_v1.debug

**Comment by khurtado** [comment]
Hi @gourangakole : No need to do so. This is needed for the CODEGEN step only. The output tries to copy via XrootD to the stash user's area but it uses condor chirp if that fails. You can see in your logfile how even though there was no stash, you still got your output transferred with the fallback method. The INTEGRATE step uses just condor for transferring the files, no stash involved.

```
mktemp: failed to create directory via template `/stash/user/gkole/tmp.XXXXXXXXXX': No such file or directory
chmod: cannot access `': No such file or directory
>> Submitting CODEGEN condor job and wait
All jobs done.
CODEGEN ran sucessfully!.
```

**Comment by gourangakole** [comment]
@khurtado Thank you for the clarification 👍
