### ISSUE TITLE
[CMSConnect] sub-job submission sometimes fails

### ISSUE THREAD

**Issue by AndreasAlbert** [cms-sw/genproductions#1627]
Hi,

for the last ~24 hours, I have been getting a type of submission error I have not seen before (error message below). I get it at varying times during gridpack generation, sometimes after hours of running peacefully. Unfortunately, the MG cluster interface cannot recover from this error. @khurtado: This is a system-side error, right? Do you know what the problem is?

Thanks

Andreas

> Some Jobs are in a Hold/... state. Error messages are below.Please try to investigate or contact the IT team.
>ClusterId 1926599 with HoldReason: Error from slot1@glidein_139254_88327360@batch0448.desy.de: > Failed to execute '/var/lib/condor/execute/dir_139017/glide_2f6pm2/condor_job_wrapper.sh' with arguments /var/lib/condor/execute/dir_139017/glide_2f6pm2/execute/dir_3895/condor_exec.exe survey.sh 6.156 2:  glexec call exited with status 203 and with error output ([gLExec]:  LCMAPS failed.; The reason can be found in the syslog.)
Cluster Error detected. Do you want to clean the queue? ("c"=continue the run anyway) [y, n, c][60s to answer]
>done not valid argument. Valid argument are in (y,n,c).
please retry
Error detected in "generate_events pilotrun"
write debug file /local-scratch/aalbert/dm_monozll_spin0/genproductions/bin/MadGraph5_aMCatNLO/DMSimp_MonoZLL_S_NoTau_AllInitial_MY0-750_mxd-1/DMSimp_MonoZLL_S_NoTau_AllInitial_MY0-750_mxd-1_gridpack/work/processtmp/pilotrun_tag_1_debug.log
If you need help with this issue please contact us on https://answers.launchpad.net/mg5amcnlo

**Comment by khurtado** [comment]
@AndreasAlbert Thanks for reporting! This is a Site problem, `T2_DE_DESY` is having LCMAPS issues, so I have blacklisted the site until they solve the issue. Should shouldn't see this again.

To handle other site going wrong in this way in the future, I will be adding the hold code to the machinery so that the MG cluster interface can just release the job to run somewhere else if this is encountered in the future.

**Comment by AndreasAlbert** [comment]
@khurtado Thank you for once again being super-efficient at fixing stuff!
