### ISSUE TITLE
[CMSConnect] No space left on device

### ISSUE THREAD

**Issue by AndreasAlbert** [cms-sw/genproductions#1663]
Hi @khurtado,

I am trying to run the Vjets NLO gridpacks from the mg26x HEAD and my codegen jobs get `No space left on device` errors (see [1]). The codegen log is at [2].  Can you see whether there is a system problem or are the jobs doing something stupid?

It appears that in 1 of ~10 tries, the problem does not appear (successful job ran on `Linux node106.local 2.6.32-696.18.7.el6.x86_64`). Running locally works fine.

NB: The log does not reflect the error because the codegen job does not seem to realize it failed. The integration job then fails because the codegen output is nonsense.

Thanks

Andreas

[1] https://gist.github.com/AndreasAlbert/885cae706c01560598bfd84795c3ba3e
[2] https://gist.github.com/AndreasAlbert/cfb0f2f2f8ad1cc5e5e041a0b4356163

**Comment by khurtado** [comment]
@AndreasAlbert: Interesting, could you try doing:
```
export _CONDOR_JOB_DEFAULT_REQUESTDISK="8*1024*1024"
```
before running the submission script? (or whatever space you think your `codegen` will require)
If that works, i will need to add the requestdisk as a parameter in the scripts

**Comment by AndreasAlbert** [comment]
@khurtado Thanks for your suggestion, I think it helped. I am still a bit confused because when I ran locally, the folder size never exceeded ~5 GB, but now I need to use REQUESTDISK values of 12 or even 20 GB to make it run. Not sure if that makes sense.
