### ISSUE TITLE
[mg26x] MadSpin crashes when decaying events after gridpack generated succesfully

### ISSUE THREAD

**Issue by cmantill** [cms-sw/genproductions#1670]
I produced gridpacks for WJetsToQQ process at NLO usng M.G. 26x and these cards:

https://github.com/cmantill/genproductions/tree/mg26x/bin/MadGraph5_aMCatNLO/cards/production/13TeV/WJetsToQQ_5f_NLO_FXFX_bias
https://github.com/cmantill/genproductions/tree/mg26x/bin/MadGraph5_aMCatNLO/cards/production/13TeV/WJetsToQQ_5f_NLO_FXFX

both gridpacks where generated succesfully (although they took some time to generate), e.g. see the log here:

http://cmantill.web.cern.ch/cmantill/gridpack_generationWJetsbias.log

However, when I untar the gridpack and test it in a CMSSW env (9_3_0), I obtain the following error:
INFO: 
   --------------------------------------------------------------
      Summary:
      Process p p > V [QCD] @0 ; p p > V j [QCD] @1 ; p p > V j j [QCD] @2
      Run at p-p collider (6500.0 + 6500.0 GeV)
      Number of events generated: 1000
      Total cross section, incl. bias (DO NOT USE): 3.302e+14 +- 1.2e+12 pb
   --------------------------------------------------------------
 
INFO: The /local-scratch/cmantil1/CMSSW_7_1_30/src/process/Events/cmsgrid/events.lhe.gz file has been generated.
 
INFO: Events generated 
reweight -from_cards
decay_events -from_cards
INFO: Running MadSpin 
INFO: This functionality allows for the decay of resonances 
INFO: in a .lhe file, keeping track of the spin correlation effets. 
INFO: BE AWARE OF THE CURRENT LIMITATIONS: 
INFO:   (1) Only a succession of 2 body decay are currently allowed 
************************************************************
*                                                          *
*           W E L C O M E  to  M A D S P I N               *
*                                                          *
************************************************************
INFO: Extracting the banner ... 
INFO: process: p p > V   
INFO: options:  
INFO: detected model: loop_sm-ckm_no_b_mass. Loading... 
set seed 1023747
set seed 1010835
set seed 1016767
set seed 1025432
set ms_dir ./madspingrid
set Nevents_for_max_weigth 250 # number of events for the estimate of the max. weight
set max_weight_ps_point 400  # number of PS to estimate the maximum for each event
set BW_cut 40                # cut on how far the particle can be off-shell
set max_running_process 1
define q = u c d s b u~ c~ d~ s~ b~
define q = u c d s b u~ c~ d~ s~ b~
Defined multiparticle q = u c d s b u~ c~ d~ s~ b~
decay w+ > q q
decay w- > q q
launch
Command "launch -ox -n cmsgrid" interrupted with error:
AttributeError : 'NoneType' object has no attribute 'replace'
Please report this bug on https://bugs.launchpad.net/mg5amcnlo
More information is found in '/local-scratch/cmantil1/CMSSW_7_1_30/src/process/cmsgrid_tag_1_debug.log'.
Please attach this file to your report.
quit
INFO:  

I attach the debug log file here: http://cmantill.web.cern.ch/cmantill/cmsgrid_tag_1_debug.log

But when I try to get make the decay myself ( I downloaded Madgraph 2.6 and installed locally) from the events_undecayed file, it works and I get the same exact output as the one in the log file.
[madspinWJetsbias.log](https://github.com/cms-sw/genproductions/files/1715358/madspinWJetsbias.log)

I compared the two versions of MadSpin (locally and from the gridpack) and they seem very different. Is the version packed in the gridpack the correct one? Do you have any suggestions on how to solve this without running again the gridpack? Is very time consumming. 

For reference the gridpacks are located here:
ls ~cmantill/work/public/gridpacks/bias_validation/WJetsToQQ_5f_NLO_FXFX_*

Thanks!

**Comment by AndreasAlbert** [comment]
@cmantill Regarding the Madspin version: Are you sure you compared the gridpack to MG 2.6.**0** from launchpad? When I do that, I do not see any differences. I suspect you may have compared to 2.6.**1**, which indeed has some changes to madspin.

**Comment by AndreasAlbert** [comment]
Semi-useful note: Adding a simple check on line 644 of `interface_madspin.py` circumvents the problem:
`if not decay2['path']: continue`
This of course begs the question of why this happens in the first place.

**Comment by AndreasAlbert** [comment]
It seems that there is decay with ~0 BR with all attributes except BR set to "None": 
`{'matrix_element': None, 'finals': None, 'br': 1.1102230246251565e-16, 'base_order': None, 'path': None, 'decay_tag': None, 'decay_struct': None}`

The 6 wanted decays are present (+same for wplus):
`
./madspingrid/full_me/SubProcesses/P2_uxcx_wmguxsx_wm_dux 0.3163456 ('wm_dux',)
./madspingrid/full_me/SubProcesses/P2_uxcx_wmguxsx_wm_dcx 0.01690461 ('wm_dcx',)
./madspingrid/full_me/SubProcesses/P2_uxcx_wmguxsx_wm_sux 0.01690412 ('wm_sux',)
./madspingrid/full_me/SubProcesses/P2_uxcx_wmguxsx_wm_scx 0.3163456 ('wm_scx',)
./madspingrid/full_me/SubProcesses/P2_uxcx_wmguxsx_wm_bux 3.802001e-06 ('wm_bux',)
./madspingrid/full_me/SubProcesses/P2_uxcx_wmguxsx_wm_bcx 0.0005602024 ('wm_bcx',)
`

**Comment by cmantill** [comment]
Hi @AndreasAlbert, yes I downloaded MG5_aMC_v2.6.0.tar.gz from launchpad. I'm sorry I don't think MadSpin has changes but I do think other folders e.g. models/template_files/fortran/ had changes, so not sure if we are actually saving the correct version of madgraph in the gridpack.

So all these decays that are shown when I ran MadSpin locally are present? 
INFO: decay channels for w- : ( width = 2.049973 GeV )
INFO:        BR                 d1  d2
INFO:    3.163456e-01            d  u~
INFO:    3.163456e-01            s  c~
INFO:    1.110039e-01            e-  ve~
INFO:    1.110039e-01            mu-  vm~
INFO:    1.109283e-01            ta-  vt~
INFO:    1.690461e-02            d  c~
INFO:    1.690412e-02            s  u~
INFO:    5.602024e-04            b  c~
INFO:    3.802001e-06            b  u~
INFO:
INFO:
INFO: decay channels for w+ : ( width = 2.049973 GeV )
INFO:        BR                 d1  d2
INFO:    3.163456e-01            d~  u
INFO:    3.163456e-01            s~  c
INFO:    1.110039e-01            e+  ve
INFO:    1.110039e-01            mu+  vm
INFO:    1.109283e-01            ta+  vt
INFO:    1.690461e-02            d~  c
INFO:    1.690412e-02            s~  u
INFO:    5.602024e-04            b~  c
INFO:    3.802001e-06            b~  u

**Comment by cmantill** [comment]
What I don't understand is why does MadSpin runs normally in the gridpack generation

**Comment by AndreasAlbert** [comment]
The reason it runs normally is that the crash only happens because MG detects that the madspingrid folder has been moved from its original location. It then tried to make up for that by changing all previously stored paths. This piece of code does handle the case of a path being unset, so that's where the crash comes from. Apparently all other parts of Madspin are fine with unset paths, so that the crash does not appear again.

**Comment by AndreasAlbert** [comment]
I asked the MG authors whether or not this is expected: https://answers.launchpad.net/mg5amcnlo/+question/664319

Let's see what they say.

**Comment by AndreasAlbert** [comment]
Olivier replied saying that it is safe to apply the simple patch I described above. @kdlong @agrohsje should we add a patch for this?

**Comment by AndreasAlbert** [comment]
(Olivier has committed the patch to 2.6.2)

https://bazaar.launchpad.net/~mg5core1/mg5amcnlo/2.6.2/revision/305

**Comment by AndreasAlbert** [comment]
Fixed in https://github.com/cms-sw/genproductions/pull/1697

Can be closed.
