### ISSUE TITLE
[mg/cmsconnect] unzip command not found

### ISSUE THREAD

**Issue by AndreasAlbert** [cms-sw/genproductions#1705]
Hi @khurtado,

I encounter a problem when trying to produce a gridpack using model files in `zip` format.
The codegen job dies with this error:
`gridpack_generation.sh: line 288: unzip: command not found`

Is the unzip command not available on all sites? My log says:

`Running on  Linux cabinet-0-0-23.t2.ucsd.edu 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Jan 4 17:31:22 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Is there an alternative on that site?

**Comment by khurtado** [comment]
Hi Andreas,
Good catch. Yes,  `unzip` is not part of the CMSSW software and while common, it's not a standard tool in linux in general.

Could you try this patch? It basically transfers unzip for the `codegen` step in case it's not available in the worker node. 
https://github.com/khurtado/genproductions/tree/patch-9

You can do

```
export CONDOR_DEFAULT_DESIRED_SITES="T2_US_UCSD"
```
before submitting your gridpack to match to that site only, for testing.

**Comment by AndreasAlbert** [comment]
@khurtado: Thanks for providing this solution! Your patch works perfectly.

**Comment by khurtado** [comment]
@AndreasAlbert Thanks for testing it! I made the PR to have it fixed in the main branch.
