### ISSUE TITLE
not able to produce proper gridpack

### ISSUE THREAD

**Issue by abdollah110** [cms-sw/genproductions#1715]
Hi
I need to prepare the gridpack for my signal using cms-connect. I do receive the .log and .debug file but apparently, the .tar.xz file which I receive is not the proper gridpack file. I have copied the log file and the .xz file in my public area.
/afs/cern.ch/user/a/abdollah/public/Codex_LQ1500_DM_500_X_550_gen2

Can you please have a look at that and let me know what's going wrong?

**Comment by abdollah110** [comment]
To provide a bit more info, when I compare my output.log with the log file of one of the successful file from Andreas, I see the following difference:

------------------------
Last part of my XXX.log:
Creating tarball
+ '[' 1 -gt 0 ']'
+ XZ_OPT=--lzma2=preset=2,dict=256MiB
+ mkdir InputCards
+ cp /local-scratch/abdollah/genproductions/bin/MadGraph5_aMCatNLO/Codex_LQ1500_DM_500_X_550_gen2/Codex_LQ1500_DM_500_X_550_gen2_customizecards.dat /local-scratch/abdollah/genproductions/bin/MadGraph5_aMCatNLO/Codex_LQ1500_DM_500_X_550_gen2/Codex_LQ1500_DM_500_X_550_gen2_extramodels.dat /local-scratch/abdollah/genproductions/bin/MadGraph5_aMCatNLO/Codex_LQ1500_DM_500_X_550_gen2/Codex_LQ1500_DM_500_X_550_gen2_gridpack /local-scratch/abdollah/genproductions/bin/MadGraph5_aMCatNLO/Codex_LQ1500_DM_500_X_550_gen2/Codex_LQ1500_DM_500_X_550_gen2_output.tar.xz /local-scratch/abdollah/genproductions/bin/MadGraph5_aMCatNLO/Codex_LQ1500_DM_500_X_550_gen2/Codex_LQ1500_DM_500_X_550_gen2_proc_card.dat /local-scratch/abdollah/genproductions/bin/MadGraph5_aMCatNLO/Codex_LQ1500_DM_500_X_550_gen2/Codex_LQ1500_DM_500_X_550_gen2_run_card.dat InputCards
cp: omitting directory `/local-scratch/abdollah/genproductions/bin/MadGraph5_aMCatNLO/Codex_LQ1500_DM_500_X_550_gen2/Codex_LQ1500_DM_500_X_550_gen2_gridpack'
~                                                                                                                                                               

------------------------
Last part of a successful job submission XXX.log:

Creating tarball
+ '[' 1 -gt 0 ']'
+ XZ_OPT=--lzma2=preset=2,dict=256MiB
+ mkdir InputCards
+ cp /local-scratch/aalbert/run/2018-03-05_forAbdollah/genproductions/bin/MadGraph5_aMCatNLO/./cards/production/2017/13TeV/DarkMatter_MonoLQ2//Codex_LQ1200_DM_450_X_495_gen2/Codex_LQ1200_DM_450_X_495_gen2_customizecards.dat /local-scratch/aalbert/run/2018-03-05_forAbdollah/genproductions/bin/MadGraph5_aMCatNLO/./cards/production/2017/13TeV/DarkMatter_MonoLQ2//Codex_LQ1200_DM_450_X_495_gen2/Codex_LQ1200_DM_450_X_495_gen2_extramodels.dat /local-scratch/aalbert/run/2018-03-05_forAbdollah/genproductions/bin/MadGraph5_aMCatNLO/./cards/production/2017/13TeV/DarkMatter_MonoLQ2//Codex_LQ1200_DM_450_X_495_gen2/Codex_LQ1200_DM_450_X_495_gen2_proc_card.dat /local-scratch/aalbert/run/2018-03-05_forAbdollah/genproductions/bin/MadGraph5_aMCatNLO/./cards/production/2017/13TeV/DarkMatter_MonoLQ2//Codex_LQ1200_DM_450_X_495_gen2/Codex_LQ1200_DM_450_X_495_gen2_run_card.dat InputCards
+ EXTRA_TAR_ARGS=
+ '[' -e /local-scratch/aalbert/run/2018-03-05_forAbdollah/genproductions/bin/MadGraph5_aMCatNLO/./cards/production/2017/13TeV/DarkMatter_MonoLQ2//Codex_LQ1200_DM_450_X_495_gen2/Codex_LQ1200_DM_450_X_495_gen2_externaltarball.dat ']'
+ XZ_OPT=--lzma2=preset=2,dict=256MiB
+ tar -cJpsf /local-scratch/aalbert/run/2018-03-05_forAbdollah/genproductions/bin/MadGraph5_aMCatNLO/Codex_LQ1200_DM_450_X_495_gen2_slc6_amd64_gcc481_CMSSW_7_1_30_tarball.tar.xz mgbasedir process runcmsgrid.sh gridpack_generation.log gridpack_generation_codegen.log InputCards
+ echo 'Gridpack created successfully at /local-scratch/aalbert/run/2018-03-05_forAbdollah/genproductions/bin/MadGraph5_aMCatNLO/Codex_LQ1200_DM_450_X_495_gen2_slc6_amd64_gcc481_CMSSW_7_1_30_tarball.tar.xz'
Gridpack created successfully at /local-scratch/aalbert/run/2018-03-05_forAbdollah/genproductions/bin/MadGraph5_aMCatNLO/Codex_LQ1200_DM_450_X_495_gen2_slc6_amd64_gcc481_CMSSW_7_1_30_tarball.tar.xz
+ echo 'End of job'
End of job
+ '[' gridpack_generation.sh '!=' gridpack_generation.sh ']'
+ exit 0

**Comment by abdollah110** [comment]
Is there anybody taking responsibility of looking at issues?

**Comment by agrohsje** [comment]
I see
Cross-section :   1.153e-16 +- 4.089e-19 pb
in the log. Is that what you expect ?

**Comment by abdollah110** [comment]
I am not sure we can rely on the cross section from Madgraph?
Anyway, I guess there is something wrong that "EXTRA_TAR_ARGS" setting is missing in my log file!?

**Comment by agrohsje** [comment]
For me, there could be 2 issues. A pure technical one, or a physics one causing technical problems. For the former one, @khurtado might be able to say more, but at this point I am really puzzled about the cross section results and the model. Was that validated in MCI? Why should the cross section by MG5_aMC@NLO be wrong by several orders of magnitude but the rest of the simulation ok?

**Comment by kdlong** [comment]
EXTRA_TAR_ARGS is intended to be empty for most gridpacks.

**Comment by kdlong** [comment]
I see no errors until the gridpack isn't copied over at the end. @khurtado could this just be a transient write error on /local-scratch?

@abdollah110 did you try resubmitting?

**Comment by abdollah110** [comment]
Yes, I have tried multiple times!! I get several log files and even a file which is called Codex_LQ1500_DM_500_X_550_gen2_output.tar.xz, but apparently this is not the gridpack one!

**Comment by kdlong** [comment]
Ok I think I see the error. What's the content of you $CARDSDIR, e.g. the directory you pass to the scripts as cards/production/2017/13TeV/XXX. It seems to have a subdirectory which is causing the card copy lines in the script to exit with an error.

https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L759

gives the ```cp: omitting directory``` error you see at the end of the log which triggers the exit unfortunately.

**Comment by abdollah110** [comment]
Great!
Thanks, it is fixed now.

**Comment by khurtado** [comment]
Sorry for being late to the party, glad it's figured out already. 
@kdlong: Are there other situations in which `cards` could have sub-directories (empty or not)? . Do you think `cp -r` should be put in place in there to avoid that error?

**Comment by kdlong** [comment]
I don't think there is ever a case where there should be a directory in the cards folder, so I'm not sure you'd want to just blindly copy over whatever is there. But I agree that failing at the very final step because of this is silly. It should be sufficient to change it instead to be ```cp $CARDSDIR/*.*``` or to just ```set +e``` before this step, does that seem reasonable to you?

**Comment by khurtado** [comment]
@kdlong: Agree. I would prefer the `cp $CARDSDIR/*.*` if it is certain we will never need files without extensions

**Comment by abdollah110** [comment]
Indeed the main reason for the failure was that my directory where the Madgraph cards where located, Codex_LQ1300_DM_500_X_550_gen2,  was in ./ directory. I moved it elsewhere and it is fine now. At the end of the job, a new directory with this name is created in ./ directory. Previously because such folder existed here, the jobs failed, but now there is no error
