### ISSUE TITLE
[MG]Requesting model file upload

### ISSUE THREAD

**Issue by sihyunjeon** [cms-sw/genproductions#1784]
Hi,

our group is working on LRSM analysis and there has been model card in [1] made by Richard Ruiz, etc.
Can this model card be uploaded to [2]?

Thanks, Sihyun.

[1] http://feynrules.irmp.ucl.ac.be/wiki/EffLRSM
[2] https://cms-project-generators.web.cern.ch/cms-project-generators/

**Comment by perrozzi** [comment]
is this http://feynrules.irmp.ucl.ac.be/raw-attachment/wiki/EffLRSM/EffLRSM_NLO.tgz the file you want to use?

**Comment by sihyunjeon** [comment]
Yes that is the one, thanks!

**Comment by sihyunjeon** [comment]
Hi is this model card added?

**Comment by qliphy** [comment]
@sihyunjeon   Added now.
