### ISSUE TITLE
[CMS connect] Disk quota exceede

### ISSUE THREAD

**Issue by cmantill** [cms-sw/genproductions#1792]
Hi @khurtado,

I'm trying to generate ZJetstoQQ at LO using cmsconnect. These are the cards up to 4j https://github.com/cms-sw/genproductions/tree/master/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/ZJets_LO_MLM/ZJetsToQQ_HT600to800.

I am getting this error [1] and this is the log [2]. I have tried  increasing space by doing this command export _CONDOR_JOB_DEFAULT_REQUESTDISK="20*1024*1024" but does not seem to work. This is the command I am using to submit: 

nohup ./submit_cmsconnect_gridpack_generation.sh ZJetsToQQ_HT600to800 cards/production/2017/13TeV/ZJets_LO_MLM/ZJetsToQQ_HT600to800/ 1 "20 Gb" > mysubmit_ZJetsToQQ_HT600to800_4j.debug 2>&1 & 

Is this a memory problem? Or space? I can't really tell from the logs what is happening.
Any help would be greatly appreciated!
Thanks
Cristina

[2] http://cmantill.web.cern.ch/cmantill/tmp/ZJetsToQQ_HT600to800_2.log
[1] http://cmantill.web.cern.ch/cmantill/tmp/pilotrun_ZJets_debug.log

**Comment by khurtado** [comment]
Hi @cmantill,

Looks like condor is not detecting the expression and hence not doing the multiplication for some reason. Could you try instead:

```
_CONDOR_JOB_DEFAULT_REQUESTDISK=20971520
```

**Comment by khurtado** [comment]
Hi @cmantill 

I think `T2_CH_CSCS` is advertising more disk space than they have. I blacklisted the site temporarily and will report the issue to them. Could you log out and log in back and try again?

**Comment by khurtado** [comment]
@cmantill Can we consider this fixed, or are you still getting disk quota issues?

**Comment by cmantill** [comment]
Yes, thanks this seemed to do the trick!
