### ISSUE TITLE
[CMS Connect] Issue running mg242 gridpacks

### ISSUE THREAD

**Issue by lviliani** [cms-sw/genproductions#1906]
Hi, 

I am trying to generate some mg242 gridpacks with CMS Connect following the instructions in the Madgraph twiki page, but they are failing with this strange error:

`Submitting job(s).`
`1 job(s) submitted to cluster 4692931.`
`>> Start CODEGEN step`
`>> Submitting CODEGEN condor job and wait`
`Couldn't understand job number: cms.org.cern`

This happens because when running, e.g.

`condor_submit codegen_dyellell01234j_4f_LO_MLM.jdl`

the output is

`Submitting job(s)`
`No ProjectName ClassAd defined!`
`Please run "connect project" to set your default project.`
`Alternatively, define your CMS Connect project ID in your submit file.`
	` Example:  +ProjectName = "MyProjectName"`
`The following projects are available to you:`
	` cms.org.cern`

Adding `+ProjectName =  "cms.org.cern"` in the jdl file solves the problem.
Another solution that works for me is adding the project name in this file:
`$HOME/.ciconnect/defaultproject`

@khurtado Have you ever seen this kind of error before? Do I have to set the project name by hand or have I missed something?

Thanks a lot!

**Comment by khurtado** [comment]
Hi @lviliani ,

Yes, that (adding a default project in `$HOME/.ciconnect/defaultproject`) and setting up user grid certificates are a pre-requirement before submitting the jobs. All users get those instructions by email after approval. You should have gotten such email after you were approved.

**Comment by lviliani** [comment]
Hi @khurtado ,

thanks a lot! I had completely missed that part.
