### ISSUE TITLE
automatic nFinal check is (sometimes?) wrong

### ISSUE THREAD

**Issue by hroskes** [cms-sw/genproductions#2154]
```
[hroskes@lxplus004 utils]$ python request_fragment_check.py --prepid HIG-RunIIFall17wmLHEGS-03433 --bypass_status
---> 1 request will be checked:

Current date and time: 2019-03-24 19:20:36
HIG-RunIIFall17wmLHEGS-03433

***********************************************************************************
HIG-RunIIFall17wmLHEGS-03433    Status= new
ZZTo4L_13TeV_powheg_pythia8
nFinal=2
/cvmfs/cms.cern.ch/phys_generator/gridpacks/2017/13TeV/powheg/V2/ZZTo4L/v1/ZZ_slc6_amd64_gcc630_CMSSW_9_3_0_ZZTo4L2017_pdf306000.tgz
/eos/cms/store/group/phys_generator/cvmfs/gridpacks/2017/13TeV/powheg/V2/ZZTo4L/v1/ZZ_slc6_amd64_gcc630_CMSSW_9_3_0_ZZTo4L2017_pdf306000.tgz
powheg True
mg False
Data set name is regular: ZZTo4L_13TeV_powheg_pythia8
grep from powheg pwhg_checklimits files
['-5', '0', '23', '23', '11', '-11', '11', '-11', '-5']
* [ERROR] nFinal(=2) is NOT equal to the number of final state particles before decays (=7)
* [OK] no known inconsistency in the fragment w.r.t. the name of the dataset powheg
* [OK] Tune configuration probably OK in the fragment
***********************************************************************************
Number of warnings = 0
Number of errors = 1
There is at least 1 error. Request won't proceed to VALIDATION
```

This is not correct - the number of final state particles is 2.  I assumed that the final state particles were the two Z's, and this is what I have always used.  Even if that is not correct for some reason, counting both the Z's and the electrons they decay to is definitely wrong.

**Comment by qliphy** [comment]
@efeyazgan 

nFinal check indeed looks buggy here.  Probably we should further remove  leptons in this line:
                        nfinstatpar = len(nemitsplit)-nemitsplit.count('0')

Similar also happens  for HIG-RunIIFall18wmLHEGS-01283  [1], it counts nFinal as 3 from "'25', '-11', '12'".  However,  leptons from W decay should not enter the counting.   Note this process contains both HW and HWJ,  and in pwhg_checklimits file, there are different lines.  And the nFinal check works seems to be just by chance.

It would be safer to change the "ERROR" message to "Warning".


[1] 
WplusH_HToGG_WToAll_M130_13TeV_powheg_pythia8
nFinal=3
powheg True
mg False
Data set name is regular: WplusH_HToGG_WToAll_M130_13TeV_powheg_pythia8
grep from powheg pwhg_checklimits files
['-1', '2', '25', '-11', '12', '0', '0']

**Comment by efeyazgan** [comment]
Yes, we should definitely change it warning anyway but isn't there any case where we need to count leptons?

**Comment by qliphy** [comment]
>>"but isn't there any case where we need to count leptons?"
Yes, it could be, for example, I think for process like DY p p > l+ l-

**Comment by efeyazgan** [comment]
Thanks for your inputs. 

Now master has the new code. Please see the changes in https://github.com/cms-sw/genproductions/commit/19fde99e82ea29f3307ade27df696c106bff7d69#diff-d3e43c7a91a85459f5db4a6444ef2827

I am closing the issue.
