### ISSUE TITLE
[CMSconnect, tt012j_5f_ckm_NLO_FXFX] Impossible to compile /work/processtmp/madspingrid/full_me/Source directory

### ISSUE THREAD

**Issue by gkrintir** [cms-sw/genproductions#2155]
Hello,

I am trying to produce a [tt012j_5f_ckm_NLO_FXFX_NNLO3p1](https://github.com/cms-sw/genproductions/tree/mg242legacy/bin/MadGraph5_aMCatNLO/cards/production/2017/13TeV/tt012j_5f_ckm_NLO_FXFX_NNLO3p1) gridpack ([mg242legacy](https://github.com/cms-sw/genproductions/tree/mg242legacy/bin/MadGraph5_aMCatNLO) branch) on CMSconnect, but I am repeatedly getting a Madsping error:

> ^[[1;31mCommand "launch -n pilotrun" interrupted with error:
> MadGraph5Error : Impossible to compile [1]/tt012j_5f_ckm_NLO_FXFX_NNLO3p1_gridpack/work/processtmp/madspingrid/full_me/Source directory
>         Trying to launch make command returns:
>             [Errno 12] Cannot allocate memory
>         In general this means that your computer is not able to compile.

I am running as:

> nohup ./submit_cmsconnect_gridpack_generation.sh tt012j_5f_ckm_NLO_FXFX_NNLO3p1 cards/production/2017/13TeV/tt012j_5f_ckm_NLO_FXFX_NNLO3p1 1 "8 Gb" > mysubmit2_tt012j_5f_ckm_NLO_FXFX_NNLO3p1.debug 2>&1 &

Have you encountered smth similar? Logs are in [1].

Regards and many thanks in advance!

[1] /local-scratch/gkrintir/v5/genproductions/bin/MadGraph5_aMCatNLO/tt012j_5f_ckm_NLO_FXFX_NNLO3p1

**Comment by lviliani** [comment]
Hi,

you should put log files in a public area if you want us to check them.

In any case I think we have seen this problem already. It should be related to the fact that the Madspin step is run on the login node with CMS Connect, and the available memory on this node is not enough.

I would suggest to try the gridpack production using CERN HT Condor instead.

**Comment by gkrintir** [comment]
Thanks a lot @lviliani 

I am then trying with CERN HT Condor and come back to report.

Regards

PS: I think the /local-scratch/ area is public but you are right we shouldn;t expect everyone to have a CMS Connect account. I'll copy them under some public area on /afs.

**Comment by gkrintir** [comment]
Hello,

I can confirm that on batch the gridpack is successfully created (*).

@qliphy @efeyazgan  Would it be possible to add at least a comment/note on [QuickGuideMadGraph5aMCatNLO](https://twiki.cern.ch/twiki/bin/viewauth/CMS/QuickGuideMadGraph5aMCatNLO#Gridpack_generation_on_the_grid) that the 
available memory on the node is not enough for CMS Connect so that there are instances that Madspin cannot compile? So that the user may be aware of and makes use of alternative methods.

Regards and many thanks!

(*) Just to mention once more I am talking about FxFx in 2.4.2; in 2.6.0 I also got what @lviliani reports in [Mg26xTests](https://twiki.cern.ch/twiki/bin/viewauth/CMS/Mg26xTests#ttbar_MG5_aMC_NLO_MLM_DONE) for MLM but I haven't tried what happens with FxFx.

**Comment by qliphy** [comment]
@gkrintir   Thanks!  We have added a comment there:  Note however as Madspin step runs on the login node with CMS Connect, there can be compiling issue as the available memory on the login node may not be enough for complicated cases. See e.g. link1 and link2.

**Comment by gkrintir** [comment]
Thanks a lot @qliphy 

We can close the issue now. ;D

Regards
