### ISSUE TITLE
request_fragment_check and randomized parameters requests with gridpacks

### ISSUE THREAD

**Issue by DryRun** [cms-sw/genproductions#2385]
request_fragment_check doesn't work on randomized parameters requests with gridpacks :

```
Traceback (most recent call last):
  File "request_fragment_check.py", line 546, in <module>
    gridpack_cvmfs_path = gridpack_cvmfs_path.split('\'')[1]
IndexError: list index out of range
```

The line of the [fragment](https://cms-pdmv.cern.ch/mcm/edit?db_name=requests&prepid=EXO-RunIISummer15GS-14142&page=0) in question is:

```
grid_points = [{"gridpack_path": "/cvmfs/cms.cern.ch/phys_generator/gridpacks/2017/13TeV/madgraph/V5_2.6.1/ttbarDM_inclusive_DMsimp_LO/ttbarDM__inclusive__DMsimp_LO_s_spin0__mchi_1_mphi_50_gSM_1_gDM_1_6500GeV_slc6_amd64_gcc630_CMSSW_9_3_8_tarball.tar.xz", "processParameters": ["JetMatching:setMad = off", "JetMatching:scheme = 1", "JetMatching:merge = on", "JetMatching:jetAlgorithm = 2", "JetMatching:etaJetMax = 5.", "JetMatching:coneRadius = 1.", "JetMatching:slowJetPower = 1", "JetMatching:qCut = 90", "JetMatching:nQmatch = 5", "JetMatching:nJetMax = 1", "JetMatching:doShowerKt = off", "Check:epTolErr = 0.0003", "SLHA:minMassSM = 0.1"], "name": "/TTbarDMJets_Inclusive_scalar_LO_Mchi-1_Mphi-50_TuneCP5_13TeV-madgraph-mcatnlo-pythia8", "weight": 0.16748768472906403},...
``` 

which fails because the splitting logic is looking for a line in `externalLHEProducer` like `args = cms.vstring('/cvmfs/cms.cern.ch/phys_generator/gridpacks/2017/13TeV/madgraph/V5_2.6.0/some_model/some_gridpack_slc6_amd64_gcc630_CMSSW_9_3_8_tarball.tar.xz'),`. 

While it's easy enough to adapt the code to search for the gridpack path(s) more robustly (`re_gridpack = re.compile("/cvmfs/cms\.cern\.ch/phys_generator/gridpacks/.*?(tar.xz|tgz); gridpacks = re_gridpack.findall(gridpack_string)`), it looks like a large amount of work to adapt the code to actually validate each randomized parameter point. Additionally, there is no standard for making randomized parameter requests, i.e. I made a list of dictionaries named `grid_points` that is used by a loop to fill the `VPSet`, but another request might just create the `VPSet` directly; this makes validation via string parsing difficult. 

I don't have a good idea for how to address this, but some thoughts:
- Making the script more modular would help for making a loop over the grid points. 
- If CMSSW is setup, the fragment could be loaded, and the `PSet` itself could be used for the validation (this is how I created `grid_points` in the first place).

**Comment by efeyazgan** [comment]
Hi @DryRun 
thanks for reporting the issue. Do you have an associated prepid? thanks.

**Comment by DryRun** [comment]
Hi @efeyazgan - sure, https://cms-pdmv.cern.ch/mcm/edit?db_name=requests&prepid=EXO-RunIISummer15GS-14142&page=0

**Comment by efeyazgan** [comment]
Hi @DryRun 
I updated the master branch with https://github.com/cms-sw/genproductions/commit/22e691db4657d3cf8dcc20d4f42e015d1c1451c0#diff-3627d2f68c58b59129e6afd65cec9079 
This checks gridpack parameters (only looking at one of the gridpacks) and for now checks nJetMax (assuming in such requests we always use the word "grid_points"). We can add more checks later and improve the code.

**Comment by DryRun** [comment]
@efeyazgan Thanks a million for the very fast fix! I think this will be fine to proceed for the moment.
