### ISSUE TITLE
Undesired errors from request checking script for LO MG+Herwig7

### ISSUE THREAD

**Issue by gvonsem** [cms-sw/genproductions#2391]
Running the [request checking script](https://github.com/cms-sw/genproductions/blob/0efab6d3b096a4658db73064e0202be8c7ebcafa/bin/utils/request_fragment_check.py) on a ttGamma MadGraph (at LO) + Herwig7 request in preparation results in a few errors:

```
TOP-RunIIFall17wmLHEGS-00347    Status= new
TTGamma_SingleLept_TuneCH3_13TeV-madgraph-herwig7
* [ERROR] Herwig7LHEMG5aMCatNLOSettings_cfi should be loaded in the fragment
* [ERROR] herwig7LHEMG5aMCatNLOSettingsBlock missing for powheg+herwig7 request
* [ERROR] hw_lhe_MG5aMCatNLO_settings missing for powheg+herwig7 request
```

As far as I know, the [herwig7LHEMG5aMCatNLOSettingsBlock](https://github.com/cms-sw/cmssw/blob/master/Configuration/Generator/python/Herwig7Settings/Herwig7LHEMG5aMCatNLOSettings_cfi.py) is only needed when MG5aMCatNLO is run in the NLO mode. Therefore, even though they probably will not affect anything in LO calculations, in principle the fragment should not be wrong when the block is left out. This was confirmed by @Andrej-CMS.  

One solution may be to distinguish the "madgraph" case from "mcatnlo" in the [request checking script](https://github.com/cms-sw/genproductions/blob/0efab6d3b096a4658db73064e0202be8c7ebcafa/bin/utils/request_fragment_check.py#L399), at least if the convention to use "madgraph" for LO and "mcatnlo" for NLO is strict. 

In addition, the [print outs of the error](https://github.com/cms-sw/genproductions/blob/0efab6d3b096a4658db73064e0202be8c7ebcafa/bin/utils/request_fragment_check.py#L405-L409) for mcatnlo cases should not refer to powheg.

**Comment by qliphy** [comment]
Seems we should update https://github.com/cms-sw/genproductions/blob/0efab6d3b096a4658db73064e0202be8c7ebcafa/bin/utils/request_fragment_check.py#L399

@efeyazgan  can you have a look?

**Comment by efeyazgan** [comment]
@gvonsem thanks for reporting. For now we adopted your solution and also fixed the printouts.
