### ISSUE TITLE
Request_fragment_check with dev instance

### ISSUE THREAD

**Issue by harrypuuter** [cms-sw/genproductions#2425]
When performing a fragment check on the dev instance with the `--dev` option, the wrong API url is used in this line. This way, the fragment from production McM is checked and not from devMcM

https://github.com/cms-sw/genproductions/blob/d0855a469f1ce6fe39b261a507960d3d2bde1cbd/bin/utils/request_fragment_check.py#L402

As a fix, the line should be changed to 
```python
os.system('wget -q '+mcm_link+'public/restapi/requests/get_test/'+pi+' -O '+pi+'_get_test')
```
using the `mcm_link` variable which is set corretly when using the `--dev` option

**Comment by efeyazgan** [comment]
Thanks a lot for reporting. It is fixed now.
