### ISSUE TITLE
Bug in run_pwg_condor.py

### ISSUE THREAD

**Issue by EmyrClement** [cms-sw/genproductions#2508]
Hi,

Looking at these lines:

https://github.com/cms-sw/genproductions/blob/a4a93103faa51123763e0a9b387915a2ff33744c/bin/Powheg/run_pwg_condor.py#L956-L965

it appears a merge conflict wasn't resolved before merging into master?  The script does not run.

Thanks,
Emyr

**Comment by agrohsje** [comment]
Fixed now. Thanks for reporting.
Cheers, Qiang and Alexander.
