### ISSUE TITLE
Gridpacks, LO reweighting, and missing files

### ISSUE THREAD

**Issue by kskovpen** [cms-sw/genproductions#2708]
Hello @agrohsje @qliphy, all,

I am trying to generate gridpacks in mg245 which involve EFT reweighting at LO. While the creation of gridpacks runs smoothly, the event generation results in an error due to some fortran files removed during the cleaning process. Putting these fortran files back solves the problem. Naively, I would assume that there is something fishy going on during the gridpack generation. If you have any ideas, please let me know!

Gridpack: 
/eos/user/k/kskovpen/EFT/eft_test_slc7_amd64_gcc700_CMSSW_10_2_18_tarball.tar.xz
https://cernbox.cern.ch/index.php/s/fWoX5DRCkroR8Sk

Log file from gridpack generation: 
https://cernbox.cern.ch/index.php/s/Y7JvG8jH5vi5SkI

Error when generating events:
"set max_npoint_for_channel 0" with error:
OSError : [Errno 2] No such file or directory: '/afs/cern.ch/user/k/kskovpen/EFT/genproductions/bin/MadGraph5_aMCatNLO/temp/mgbasedir/vendor/DiscreteSampler/DiscreteSampler.f'

This happens at:
echo "0" |./bin/madevent --debug reweight GridRun_${rnum}
in runcmsgrid_LO.sh

Thanks a lot in advance,

Kirill

**Comment by agrohsje** [comment]
I discussed a similar problem with @llechner yesterday. It appears from changing the width in the reweight step. If you remove this line, everything will work. Of course that is not the physic we have in mind. Let me locally explore further. We should ping Olivier.

**Comment by kskovpen** [comment]
Since the width recalculation triggers recompilation of some parts of the fortran code, probably an interim workaround could be just preserving the fortran sources (*.f) in the gridpack (not optimal, of course ..) - it makes it possible to produce events on such gridpacks with all weights present in the output LHE file. Otherwise, probably extending rwgt.pkl to also include precomputed widths could be something to explore. Anyhow, checking with Olivier on this would be great, I agree.

**Comment by agrohsje** [comment]
Indeed. We should follow-up. Do you want to propose to Olivier on the launchpad or should I do it? We should in any case add each other.

**Comment by kskovpen** [comment]
Sure, I will do it.

**Comment by kskovpen** [comment]
The issue is now being followed here: https://answers.launchpad.net/mg5amcnlo/+question/692793
