### ISSUE TITLE
Small suggestion for request_fragment_check.py

### ISSUE THREAD

**Issue by andreypz** [cms-sw/genproductions#2814]
I think it would be helpful if at these lines, the evaluation of `(8*3600/timeperevent)*filter_eff` is also printed:
https://github.com/cms-sw/genproductions/blob/0502b5bd40e745f0fb6373d820eb925ca968a4c5/bin/utils/request_fragment_check.py#L693-L697

I would propose to change the print message to something like this:
```
     print ("* [ERROR] The expected number of events is too small: %i. Either the timeperevent value is incorrect (too large) or the filter efficiency is too small. Please check, timeperevent=%.f, filter_eff=%.f") 
```

**Comment by sihyunjeon** [comment]
@agrohsje @GurpreetSinghChahal @efeyazgan 
Can you take a look at this? I am also having issues with filter efficiencies and I think it would be good to know by how much the filter efficiency should be increased in the log

**Comment by efeyazgan** [comment]
done (see https://github.com/cms-sw/genproductions/commit/d15c02781f741e3ea0c4ff07255b44fed4fe7ee8)
