### ISSUE TITLE
Madgraph Gridpack using loop_qcd_qed_sm model

### ISSUE THREAD

**Issue by michael-pitt** [cms-sw/genproductions#2924]
Dear Experts

I'm trying to create a Madgraph gridpack with loop_qcd_qed_sm model, but I meet the following error:

> UFOImportError : /afs/cern.ch/work/m/mpitt/PPS_ZX/ZZandZy/genproductions/bin/MadGraph5_aMCatNLO/ExclZZ_box/ExclZZ_box_gridpack/work/MG5_aMC_v2_7_3/models/loop_qcd_qed_sm directory is not a valid UFO model:
>        couplings.py is missing

The generated process is: `generate a a > a z [noborn=QED] QED=4`
I tried both MG2.6 and MG2.7, and I got the same error. 

I listed below a list of commands to reproduce the error on lxplus (and a link to the cards)

thank you in advance,
Michael

_**commands**_:
```
git clone https://github.com/cms-sw/genproductions.git
cd genproductions/bin/MadGraph5_aMCatNLO/
cp -r ~mpitt/public/CEP/Madgraph/ExclZY_box cards/
./gridpack_generation.sh ExclZY_box cards/ExclZY_box
```

**Comment by sihyunjeon** [comment]
Hi,
can you first check whether it runs fine with standalone madgraph?

**Comment by michael-pitt** [comment]
Hi @sihyunjeon , it works fine
```
wget https://cms-project-generators.web.cern.ch/cms-project-generators/MG5_aMC_v2.7.3.tar.gz
tar zxvf MG5_aMC_v2.7.3.tar.gz
./MG5_aMC_v2_7_3/bin/mg5_aMC ~mpitt/public/CEP/Madgraph/ExclZY_box/ExclZY_box_proc_card.dat
```
The MG code downloads the `loop_qcd_qed_sm` model successfully

**Comment by sihyunjeon** [comment]
@michael-pitt Hi,
So OK, I also checked it myself and it seems that MadGraph does download the model file from its database in standalone, if not in the models/ directory. But for the model card you are using, with gridpack generation codes (which I believe should be the same, other model cards actually can do the same) doesn't seem to download it from the database. Not sure why this is happening.

But there is a way to get away with this problem. Add <dirname>_extramodels.dat in your cards and write loop_qcd_qed_sm.tgz. This would download the model file from [1] (CMS database, I just uploaded the model file there) and proceed with this.

But you should make sure the gridpack physics results is the same with standalone ones

[1] https://cms-project-generators.web.cern.ch/cms-project-generators/
