### ISSUE TITLE
GridPack Generation fail on CMSConnect

### ISSUE THREAD

**Issue by abbas-hassani** [cms-sw/genproductions#3137]
Dear experts,

I am trying to generate GridPack on CMSConnect using "submit_cmsconnect_gridpack_generation.sh"

The process fails with the following error:

+ set -e
+ name=PPto4Leptons_2GeV_LO
+ carddir=cards/PPto4Leptons_2GeV_LO
+ queue=local
+ jobstep=ALL
++ cat /etc/redhat-release
+ export 'SYSTEM_RELEASE=CentOS Linux release 7.9.2009 (Core)'
+ SYSTEM_RELEASE='CentOS Linux release 7.9.2009 (Core)'
+ '[' -n '' ']'
+ [[ CentOS Linux release 7.9.2009 (Core) == *\r\e\l\e\a\s\e\ \6* ]]
+ [[ CentOS Linux release 7.9.2009 (Core) == *\r\e\l\e\a\s\e\ \7* ]]
+ scram_arch=slc7_amd64_gcc700
+ '[' -n '' ']'
+ [[ CentOS Linux release 7.9.2009 (Core) == *\r\e\l\e\a\s\e\ \6* ]]
+ [[ CentOS Linux release 7.9.2009 (Core) == *\r\e\l\e\a\s\e\ \7* ]]
+ cmssw_version=CMSSW_10_6_19
+ '[' -z '' ']'
++ pwd
+ PRODHOME=/srv
+ helpers_dir=/srv/genproductions/Utilities
+ helpers_file=/srv/genproductions/Utilities/gridpack_helpers.sh
+ '[' '!' -f /srv/genproductions/Utilities/gridpack_helpers.sh ']'
++ command -v git
+ '[' -x /cvmfs/oasis.opensciencegrid.org/mis/osg-wn-client/3.5/3.5.60-2/el7-x86_64/usr/bin/git ']'
++ git rev-parse --show-toplevel
fatal: Not a git repository (or any parent up to mount point /srv)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
+ helpers_dir=/bin/MadGraph5_aMCatNLO/Utilities

Talking to the CMSConnect experts, I was notified that the following are not supposed to run in CMSConnect since iscmsconnect=0

(https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L109-L119)
-------------------
    # CMS Connect runs git status inside its own script.
    if [ $iscmsconnect -eq 0 ]; then
      cd $PRODHOME
      if [ -x "$(command -v git)" ]; then
        git status
        echo "Current git revision is:"
        git rev-parse HEAD
        git diff | cat
      fi
      cd -
    fi
----------------------
But the CMS Connect submit script sets this variable to 1

(https://github.com/cms-sw/genproductions/blob/master/bin/MadGraph5_aMCatNLO/submit_cmsconnect_gridpack_generation.sh#L316)
----------------------
iscmsconnect=1 bash -x gridpack_generation.sh ${card_name} ${card_dir} ${workqueue} INTEGRATE ${scram_arch} ${cmssw_version}
----------------------

Thank you for your help,

**Comment by menglu21** [comment]
Hi, should we close this issue since the fix was performed.

**Comment by Saptaparna** [comment]
sure. I just closed it.

**Comment by Saptaparna** [comment]
Refer to https://github.com/cms-sw/genproductions/pull/3138
