### ISSUE TITLE
MadGraph patch for 29x : color flow

### ISSUE THREAD

**Issue by sihyunjeon** [cms-sw/genproductions#3192]
@freejiebao @SanghyunKo 

@agrohsjean, is this patch from report by Dominic regarding herwig color flow crash?

https://github.com/mg5amcnlo/mg5amcnlo/commit/9c4ae9eaae817205d4df70009c283ae89e2ff375#diff-dd049d583fe3d70fc3e34949d6b976c1ccf8bd8e43b5806fb156402aeb05773d

**Comment by agrohsje** [comment]
Yes. This is the one I had in mind when pinging on Skype. I asked Dominic for a 265 backport.

**Comment by sihyunjeon** [comment]
keeping this just in case we don't use latest mg29x OR madgraph authors doesn't integrate this fix to the latest mg29x release

**Comment by Saptaparna** [comment]
+1 to that.

**Comment by sihyunjeon** [comment]
confirmed with olivier that this is in the LTS mg29x version so closing
