### ISSUE TITLE
adding MG version 3.5

### ISSUE THREAD

**Issue by michael-pitt** [cms-sw/genproductions#3326]
Recently a new modeling of photon-induced processes was introduced to MG: [gamma-UPC](https://arxiv.org/abs/2207.03012). 
According to the authors, it is expected to be integrated with the newest MG release (3.5), and until then, they recommend using the standalone version, available here: `/afs/cern.ch/user/h/hshao/public/ForDavid/MG5/mg5_UPC.tar.gz` 

How can we use this version of the code in central production? Should we create a new branch (e.g. `mg5_UPC`)?

At least two analyses will be using this version of the MG code. Currently, I modify `gridpack_generation.sh` in the following way:
```
    MG=mg5_UPC$MG_EXT
    MGTAR=mg5_UPC$MG_EXT # workaround for LTS
    MGSOURCE=https://cernbox.cern.ch/remote.php/dav/public-files/dQNyBselRGsvvNz/mg5_UPC.tar.gz
```

Thanks,
Michael

**Comment by michael-pitt** [comment]
///////////////////////////
//////// UPDATE ////////
///////////////////////////

The new MG version is available in https://launchpad.net/mg5amcnlo. Can we create a new branch `mg35x` sourcing the new version?

The only modification from `m33x` should be the MG version in the `gridpack_generation.sh` file:

```
    MG=MG5_aMC_v3.5.0$MG_EXT
    MGSOURCE=https://launchpad.net/mg5amcnlo/3.0/3.5.x/+download/MG5_aMC_v3.5.0.tar.gz
```
Or keeping the old format (with files in [cms-project-generators](https://cms-project-generators.web.cern.ch/cms-project-generators/))

**Comment by Saptaparna** [comment]
Hi @michael-pitt, have you tried using the 33x branch?

**Comment by sihyunjeon** [comment]
Hi @michael-pitt as sapta mentioned, there is a development branch with 3.3. We can add one but the patches are broken as the line numbers changed. So there will be nothing different between 1. you handfixing the MGSOURCE line and 2. us handfixing the MGSOURCE line + making another branch

**Comment by agrohsje** [comment]
to add. if we make these branches, we should make sure patches are still working and fix it if not. so it is a bit more work than changing one line.
@michael-pitt note that these are development branches. nothing here is validated and cross checked against existing knowledge.

**Comment by michael-pitt** [comment]
Hi @agrohsje  and @sihyunjeon 
Thanks for your prompt replies. I see some patches gives error once I tried it with the `m33x ` branch, making the modifications mentioned above. 

Should I try the master branch? What will be your suggestion? I'm interested in placing instructions on how to run MG cards we develop for photon-photon interactions, and we need the newer version.

**Comment by Saptaparna** [comment]
@agrohsje The branch did have the relevant changes at the time because our ultimate goal was to switch to 33x. @michael-pitt what specific errors are you seeing? I would prefer that you use the 33x branch and make a PR to add/subtract a patch rather than working with an inconsistent set of patches which would make debugging even harder.

**Comment by agrohsje** [comment]
@Saptaparna  I know. What I was saying: If we start from 3.3 branch and add 3.5, the patches might not work. So it is not just changing 2 lines as @michael-pitt proposed above. It could be, but it needs testing and worst-case fixing.

**Comment by michael-pitt** [comment]
I have the following printouts:
```
patching file MadSpin/decay.py
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file MadSpin/decay.py.rej
patching file MadSpin/decay.py
Hunk #1 succeeded at 2183 (offset 2 lines).
patching file MadSpin/interface_madspin.py
Hunk #1 FAILED at 713.
1 out of 1 hunk FAILED -- saving rejects to file MadSpin/interface_madspin.py.rej
patching file MadSpin/decay.py
Hunk #1 FAILED at 2469.
1 out of 1 hunk FAILED -- saving rejects to file MadSpin/decay.py.rej
patching file MadSpin/interface_madspin.py
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file MadSpin/interface_madspin.py.rej
```

It seems that
* the part of the patch [0077-fix_madspin_dummy_decay.patch](https://github.com/cms-sw/genproductions/blob/mg33x/bin/MadGraph5_aMCatNLO/patches/0077-fix_madspin_dummy_decay.patch) is already included in [interface_madspin.py#L644-L646](https://github.com/mg5amcnlo/mg5amcnlo/blob/3.5.0/MadSpin/interface_madspin.py#L644-L646) and [decay.py#L2473-L2478](https://github.com/mg5amcnlo/mg5amcnlo/blob/3.5.0/MadSpin/decay.py#L2473-L2478)
* patch [0037-fix_madspin_max_running_process.patch](https://github.com/cms-sw/genproductions/blob/mg33x/bin/MadGraph5_aMCatNLO/patches/0037-fix_madspin_max_running_process.patch) is included in [decay.py#L3497-L3498](https://github.com/mg5amcnlo/mg5amcnlo/blob/3.5.0/MadSpin/decay.py#L3497-L3498)
* lines [0076-fix_madspin_in_gridpack.patch#L16-L30](https://github.com/cms-sw/genproductions/blob/mg33x/bin/MadGraph5_aMCatNLO/patches/0076-fix_madspin_in_gridpack.patch#L16-L30) are not commented in the new MG version, but still cause `Hunk #1 FAILED at 713` error

fixing these paths removes these warning

**Comment by sihyunjeon** [comment]
Hi,

Those won't matter and can be ignored (based on the names of the patches) as they seem to fix things what goes in MadSpin IF you do not use MadSpin. However, there could be some necessary patches even missing totally that exists in master branch (I am not sure if we have added the thread-safe patch that we discovered only one month ago exists in mg33x). So, this depends on GEN's decision but we've been stalling MG3xx validation for a while as the initial round of Run3, we agreed to start with MG29x due to some unexpected issues and currently no one is working on this.

So what I can propose is one of the following :
a. Just change the wget line to MG3xx link the one you desire to use and ignore the patches (but do need to check the thread safe patch in the master branch) with existing branches
b. Do a. but work on patches yourself and make it work (grateful if you can do this, check, and update the genproductions for us) and make a new branch MG350
b. Start with using standalone madgraph instead of gridpack setup and see if everything is working fine and wait GEN to make updates in the branch. At least my impression after chatting with GEN I think MG350 work will start sometime soon

**Comment by stahlleiton** [comment]
Hi,
What is the status of MG3.5 in central production?
I would also be interested in using Gamma-UPC for heavy-ion collisions.

**Comment by michael-pitt** [comment]
I think we can follow (b) from @sihyunjeon and make a new brunch. I tested the MG3.5 with the master, and all works well. I don't know if the patches from mg3xx are needed (at least some are not needed, but I cannot say for all). Maybe we can make mg35x from the master branch that works with pp LO, and @stahlleiton can see if it works with HI?

**Comment by stahlleiton** [comment]
ok, I also agree that working with a separate branch would help to move things forward.
@michael-pitt : let me know once you have pushed your MG3.5 setup to a genproduction branch, and I will proceed to test it for HI.

**Comment by michael-pitt** [comment]
hi @sihyunjeon,

I followed your suggestion and checked the patches:
  1. I started with the master
  2. I removed patches 36,37,38,40 (not needed anymore)
  3. I copied mg3xx patches, omitting 37,77,78 which are not needed (note patch 6 slightly changed)
  4. fixed patch 76 
All changes are here: https://github.com/cms-sw/genproductions/compare/master...michael-pitt:mg35x
I linked to https://launchpad.net/mg5amcnlo/3.0/3.5.x/+download/MG5_aMC_v3.5.2.tar.gz. Maybe once the file is uploaded to cms-project-generators.web.cern.ch I can update the link.

I'm ready to upload my branch once `mg35x` branch is created.

Regards,
Michael

**Comment by sihyunjeon** [comment]
hey i think you should start with 33x branch. 33x had some issues that were only problematic for 33x but not in 29x

**Comment by sihyunjeon** [comment]
39, 41 from master should "ideally" be included, there is some bad sampling issues that was recently discovered https://indico.cern.ch/event/1353129/#33-lessons-learned-from-run3-s but i am not sure if everything is fully compatible with 29x (if something structurally changed or could we just apply the same patch). i pinged madgraph authors

**Comment by stahlleiton** [comment]
Which are the changes in the mg33 branch that is needed on top of the master branch to use MG35?

Checking the files in the MadGraph5 directory, I see some of them appears to be outdated in MG33 (the master contains fixes for the use of python 3 and run 3 production, while MG33 still contain settings for 2017 and earlier).

**Comment by sihyunjeon** [comment]
for patches, i think most of the things have to be checked from mg33x branch
for other scripts, you should likely start from master.

sorry for not being clear on this.

**Comment by michael-pitt** [comment]
> 39, 41 from master should "ideally" be included, there is some bad sampling issues that was recently discovered https://indico.cern.ch/event/1353129/#33-lessons-learned-from-run3-s offshell W slides. but i am not sure if everything is fully compatible with 29x (if something structurally changed or could we just apply the same patch). i pinged madgraph authors

they are included (39 and 42)

**Comment by michael-pitt** [comment]
> Which are the changes in the mg33 branch that is needed on top of the master branch to use MG35?
> 
> Checking the files in the MadGraph5 directory, I see some of them appears to be outdated in MG33 (the master contains fixes for the use of python 3 and run 3 production, while MG33 still contain settings for 2017 and earlier).

This is why I started from master + I wanted to stay up to date with the migration to `el9`

**Comment by michael-pitt** [comment]
> Which are the changes in the mg33 branch that is needed on top of the master branch to use MG35?
> 
> Checking the files in the MadGraph5 directory, I see some of them appears to be outdated in MG33 (the master contains fixes for the use of python 3 and run 3 production, while MG33 still contain settings for 2017 and earlier).

0039-fix-bad_sampling.patch
0042-add-mmnl-smin.patch

**Comment by sihyunjeon** [comment]
actually one thing you should note is that el9 doesn't work with the actual production :( one needs to use containers to make the gridpacks with os 7 or 8.
gridpack can be "made" but the actual production running in el8 fails

**Comment by stahlleiton** [comment]
Thanks a lot @michael-pitt for preparing the update to MG v3.5.
@sihyunjeon : Could you create a new branch in the genproductions repository called "mg35x" (starting from the master branch)? thanks

**Comment by sihyunjeon** [comment]
@stahlleiton @michael-pitt i added mg352 branch which is identical to master.

**Comment by michael-pitt** [comment]
> @stahlleiton @michael-pitt i added mg352 branch which is identical to master.

Thanks @sihyunjeon, I made a PR. It would be great to add a MG tar file in https://cms-project-generators.web.cern.ch/cms-project-generators, before we merge the PR
