### ISSUE TITLE
reweighting samples with madspin

### ISSUE THREAD

**Issue by sihyunjeon** [cms-sw/genproductions#3657]
https://cms-talk.web.cern.ch/t/atgc-with-ewdim6nlo-ufo-for-wv-semileptonic-channel/29869/8

When madspin and reweight is used in the same gridpack, it produces wrong physics behavior as madspin itself relies on "reweighting method". This can be handled if the madspin and reweighting step order is inverted but Olivier did not work on this yet (but has plans to, not sure what the time line is though). Should we not veto such submissions in production?

**Comment by sihyunjeon** [comment]
https://github.com/cms-sw/cmssw/issues/43784#issuecomment-1979973192

Not too much related to the bug reported in the link above but this reminded me of the issue

**Comment by sihyunjeon** [comment]
@efeyazgan for the gen scripts

@bbilin @menglu21 @agrohsje @Cvico @DickyChant

**Comment by efeyazgan** [comment]
Yes, I think that makes to veto such submissions. I will implement this sometime today. I'll also take a look at the other issue you pointed to.

**Comment by sihyunjeon** [comment]
@efeyazgan hello efe, thanks for quick response! i haven't checked the issue myself though. i think someone from eft analysis should give some insights on this buggy behavior if it is really true

**Comment by efeyazgan** [comment]
From CMStalk, the conclusion seems to be what you suggested, but OK, I will wait for feedback from others before implementing this.

**Comment by agrohsje** [comment]
The issue is that madspin calculates probabilities based on the input ME. As this is changing through EFT reweighting it doesn't work properly.  So I agree on the veto as long as we have no central fix by Oliver.,

**Comment by efeyazgan** [comment]
To implement this, to understand if reweighting is on, would it be sufficient to check the existence of the ```reweight_card``` or do you know of a better way to do it?

**Comment by sihyunjeon** [comment]
technically that would be enough. existence of both madspin_card.dat and reweight_card.dat.

if @agrohsje can confirm the bug/issue we can implement this i think

**Comment by sihyunjeon** [comment]
#3658 addressed, closing it here
