### ISSUE TITLE
Running gridpack_generation.sh in interactive mode

### ISSUE THREAD

**Issue by nstrobbe** [cms-sw/genproductions#626]
What is currently the recommended way of using the gridpack_generation.sh script locally to produce a gridpack? For initial tests it is nice to just run it in a local area so that you don't have to wait for lxbatch to run your job (can take days lately).

When I try to run with
``` 
./gridpack_generation.sh processname cardsdir
```
it does not work because there is a check for unused variables. 

https://github.com/cms-sw/genproductions/blob/f7bb0dfad24749c1163f9ca42b6153664eaaa9ab/bin/MadGraph5_aMCatNLO/gridpack_generation.sh#L46

When I remove that line, the generation proceeds as expected. 
It would be good if there was a supported way to create the gridpack locally without having to modify the script itself.

**Comment by bendavid** [comment]
Hi Nadja,
What exactly is the error you get?  (ie on which line does it complain about unset variables?)

**Comment by nstrobbe** [comment]
Hi Josh,

I had this problem last week or so, but I don't have the log files anymore. I just tried again, and now it doesn't complain... Very bizarre. Perhaps there was something wrong with the shell/environment I was using at the time.
